export const PILLAR_SUBCATEGORIES: Record<string, string[]> = {
  'AI, Surveillance & Digital Rights': [
    'mass_surveillance',
    'facial_recognition',
    'neuro_rights',
    'data_harvesting',
    'data_breaches',
    'digital_rights',
    'ai_manipulation',
    'ai_ethics',
    'encryption_policy',
    'surveillance_state',
    'government_transparency',
    'whistleblower_protection',
    'osint_tools',
  ],
  'Child Safety & Human Trafficking': [
    'epstein_network',
    'institutional_abuse',
    'trafficking_networks',
    'online_exploitation',
    'celebrity_exploitation',
    'child_labor',
    'historical_abuse',
    'law_enforcement_ops',
    'systemic_failures',
  ],
  'Elections & Governance': [
    'contested_elections',
    'campaign_finance',
    'voting_infrastructure',
    'electoral_system',
    'gerrymandering',
    'voter_suppression',
    'pattern_analysis',
    'executive_action',
    'citizen_rights',
  ],
  'Energy & Suppressed Technology': [
    'uap_disclosure',
    'suppressed_inventions',
    'energy_monopolies',
    'patents',
    'nuclear_energy',
    'energy_policy',
    'energy_geopolitics',
    'pattern_analysis',
    'space_programs',
  ],
  'Environmental & Corporate Accountability': [
    'chemical_spills',
    'climate_data',
    'toxic_exposure',
    'corporate_pollution',
    'water_contamination',
    'water_rights',
    'chemical_exposure',
    'resource_extraction',
    'climate_accountability',
    'nuclear_disasters',
    'food_systems',
    'geoengineering',
  ],
  'Financial Systems & Corporate Power': [
    'money_laundering',
    'market_manipulation',
    'tax_havens',
    'insider_trading',
    'banking_dynasties',
    'institutional_power',
    'corporate_capture',
    'revolving_door',
    'labor_exploitation',
    'housing_alternatives',
    'housing_crisis',
    'public_banking',
    'monetary_policy',
    'property_rights',
    'land_enclosure',
    'patents',
  ],
  'Health & Pharma Transparency': [
    'vaccine_safety',
    'pharma_fraud',
    'historical_experiments',
    'regulatory_capture',
    'military_health',
    'lab_safety',
    'corporate_coverup',
    'insurance_system',
  ],
  'Media Manipulation & Information Control': [
    'war_propaganda',
    'corporate_media',
    'gov_media_ops',
    'social_media_censorship',
    'embedded_journalism',
    'media_trust',
    'military_media',
    'media_consolidation',
    'suppressed_stories',
    'broadcast_control',
  ],
  'Space & Black Budget Programs': [
    'uap_disclosure',
    'uap_encounters',
    'black_budget',
    'classification_secrecy',
    'space_programs',
  ],
  'War & Intelligence': [
    'cold_war_ops',
    'modern_conflicts',
    'arms_trade',
    'intelligence_failures',
    'cia_operations',
    'fbi_operations',
    'false_flag_ops',
    'foreign_intervention',
    'pentagon_operations',
    'pattern_analysis',
    'iraq_war',
    'drug_wars',
    'silicon_valley',
  ],
};

export function pillarToPath(pillar: string): string {
  return '/' + pillar
    .toLowerCase()
    .replace(/[,&]/g, '')
    .replace(/\s+/g, '_')
    .replace(/__+/g, '_')
    .replace(/^_|_$/g, '');
}
