import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

export type Document = {
  id: string;
  title: string;
  slug: string;
  description: string;
  content: string;
  source_url: string | null;
  verification_tier: 'verified' | 'corroborated' | 'preliminary';
  document_type: string;
  date_published: string | null;
  metadata: Record<string, any>;
  topic_tags?: string[];
  notes?: string;
  official_response?: string | null;
  mainstream_framing?: string | null;
  challenges?: string | null;
  dispute_status?: 'unchallenged' | 'disputed' | 'partially_debunked' | 'ongoing';
  labeled_claims?: { type: 'DOCUMENTED' | 'INFERRED' | 'CONTESTED'; text: string }[] | null;
  has_mirror?: boolean;
  created_at: string;
  updated_at: string;
};

export type Event = {
  id: string;
  title: string;
  description: string;
  event_date: string;
  pillar: string;
  document_ids: string[];
  metadata: Record<string, any>;
  created_at: string;
  updated_at: string;
};

export type DocumentConnection = {
  id: string;
  source_document_id: string;
  target_document_id: string;
  connection_type: 'references' | 'contradicts' | 'corroborates';
  description: string | null;
  created_at: string;
};

export type Tip = {
  id: string;
  contact_email: string;
  subject: string;
  message: string;
  documentation: string | null;
  status: 'new' | 'reviewing' | 'verified' | 'dismissed';
  created_at: string;
};

export type AutoGeneratedConnection = {
  id: string;
  source_document_id: string;
  target_document_id: string;
  connection_type: 'corroborates' | 'references' | 'contradicts' | 'categoryLink';
  scope: 'intra-tree' | 'cross-tree';
  confidence_score: number;
  reasoning: {
    sharedEntities: string[];
    sharedKeywords: string[];
    mentionsOther: boolean;
    sameTimePeriod: boolean;
    sameCategory: boolean;
  };
  shared_entities: string[];
  created_at: string;
  updated_at: string;
};
