import { useQuery } from '@tanstack/react-query';
import { supabase, Document, Event, AutoGeneratedConnection, DocumentConnection } from '@/lib/supabase';

export interface EnemyEntry {
  id: string;
  name: string;
  title: string;
  subtitle: string | null;
  severity: string;
  summary: string;
  key_facts: string[];
  status_tags: string[];
  evidence_documented: string;
  sources: Array<{ name: string; url: string; date: string }>;
  date_added: string;
  last_updated: string;
  footer_note?: string | null;
  sort_order?: number | null;
}

export interface PillarEssay {
  id: string;
  pillar_slug: string;
  title: string;
  subtitle: string | null;
  body_markdown: string;
  last_updated: string;
  word_count: number;
}

export function useDocuments() {
  return useQuery({
    queryKey: ['documents'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('documents')
        .select('*')
        .order('date_published', { ascending: false });
      if (error) throw error;
      return (data || []).map(doc => ({
        ...doc,
        topic_tags: (doc.metadata?.tags as string[]) || []
      })) as Document[];
    },
  });
}

export function useDocumentBySlug(slug: string | undefined) {
  return useQuery({
    queryKey: ['document', slug],
    queryFn: async () => {
      if (!slug) return null;
      const { data, error } = await supabase
        .from('documents')
        .select('*')
        .eq('slug', slug)
        .maybeSingle();
      if (error) throw error;
      return data ? ({
        ...data,
        topic_tags: (data.metadata?.tags as string[]) || []
      } as Document) : null;
    },
    enabled: !!slug,
  });
}

export function useDocumentById(id: string | undefined) {
  return useQuery({
    queryKey: ['document', 'id', id],
    queryFn: async () => {
      if (!id) return null;
      const { data, error } = await supabase
        .from('documents')
        .select('*')
        .eq('id', id)
        .maybeSingle();
      if (error) throw error;
      return data ? ({
        ...data,
        topic_tags: (data.metadata?.tags as string[]) || []
      } as Document) : null;
    },
    enabled: !!id,
  });
}

export function useRecentDocuments(limit = 10) {
  return useQuery({
    queryKey: ['documents', 'recent', limit],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('documents')
        .select('id, title, slug, updated_at, created_at, verification_tier, metadata')
        .order('updated_at', { ascending: false })
        .limit(limit);
      if (error) throw error;
      return data;
    },
  });
}

export function useNewDocumentsCount(since: Date | null) {
  return useQuery({
    queryKey: ['documents', 'count', 'new', since?.toISOString()],
    queryFn: async () => {
      if (!since) return 0;
      const { count, error } = await supabase
        .from('documents')
        .select('id', { count: 'exact', head: true })
        .gt('updated_at', since.toISOString());
      if (error) throw error;
      return count || 0;
    },
    enabled: !!since,
  });
}

export function useEvents() {
  return useQuery({
    queryKey: ['events'],
    queryFn: async () => {
      const PAGE_SIZE = 1000;
      let all: Event[] = [];
      let from = 0;
      while (true) {
        const { data, error } = await supabase
          .from('events')
          .select('*')
          .order('event_date', { ascending: false })
          .range(from, from + PAGE_SIZE - 1);
        if (error) throw error;
        if (!data || data.length === 0) break;
        all = all.concat(data as Event[]);
        if (data.length < PAGE_SIZE) break;
        from += PAGE_SIZE;
      }
      return all;
    },
  });
}

export function useEnemiesOfTruth() {
  return useQuery({
    queryKey: ['enemies_of_truth'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('enemies_of_truth')
        .select('*')
        .order('date_added', { ascending: false });
      if (error) throw error;
      return data as EnemyEntry[];
    },
  });
}

export function useDocumentConnections(docId: string | undefined) {
  return useQuery({
    queryKey: ['document_connections', docId],
    queryFn: async () => {
      if (!docId) return { manual: [], auto: [] };

      const [{ data: manualConns, error: manualError }, { data: autoConns, error: autoError }] = await Promise.all([
        supabase
          .from('document_connections')
          .select('*')
          .or(`source_document_id.eq.${docId},target_document_id.eq.${docId}`),
        supabase
          .from('auto_generated_connections')
          .select('*')
          .or(`source_document_id.eq.${docId},target_document_id.eq.${docId}`),
      ]);

      if (manualError) throw manualError;
      if (autoError) throw autoError;

      return {
        manual: (manualConns || []) as DocumentConnection[],
        auto: (autoConns || []) as AutoGeneratedConnection[],
      };
    },
    enabled: !!docId,
  });
}

export function usePillarEssay(slug: string | undefined) {
  return useQuery({
    queryKey: ['pillar_essays', slug],
    queryFn: async () => {
      if (!slug) return null;
      const { data, error } = await supabase
        .from('pillar_essays')
        .select('*')
        .eq('pillar_slug', slug)
        .maybeSingle();
      if (error) throw error;
      return data as PillarEssay | null;
    },
    enabled: !!slug,
  });
}

export function useVerifiedDocuments(limit = 200) {
  return useQuery({
    queryKey: ['documents', 'verified', limit],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('documents')
        .select('*')
        .eq('verification_tier', 'verified')
        .order('date_published', { ascending: false })
        .limit(limit);
      if (error) throw error;
      return (data || []).map(doc => ({
        ...doc,
        topic_tags: (doc.metadata?.tags as string[]) || []
      })) as Document[];
    },
  });
}
