import { useEffect, useState, useMemo } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { Document, DocumentConnection, AutoGeneratedConnection } from '@/lib/supabase';
import { Navigation } from '@/components/Navigation';
import { Footer } from '@/components/Footer';
import { SocialShare } from '@/components/SocialShare';
import { SEOHead } from '@/components/SEOHead';
import { Breadcrumb } from '@/components/Breadcrumb';
import { isUUID } from '@/lib/slugUtils';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { FileText, Calendar, ExternalLink, Shield, Download, ArrowLeft, Network, ShieldCheck, Archive, TriangleAlert as AlertTriangle } from 'lucide-react';
import { ReportBrokenLink } from '@/components/ReportBrokenLink';
import { MatrixRain } from '@/components/MatrixRain';
import { ContextAndResponse } from '@/components/ContextAndResponse';
import { NewsletterSignup } from '@/components/NewsletterSignup';
import { EpistemicLegend, renderLabeledClaims } from '@/components/EpistemicLabel';
import { formatUTCDateShort } from '@/lib/utils';
import { useDocumentBySlug, useDocumentById, useDocumentConnections, useDocuments } from '@/hooks/useSupabaseQuery';

export function DossierDetail() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const isUUIDParam = id ? isUUID(id) : false;

  const { data: docBySlug, isLoading: slugLoading } = useDocumentBySlug(!isUUIDParam ? id : undefined);
  const { data: docById, isLoading: idLoading } = useDocumentById(isUUIDParam ? id : undefined);

  const document = isUUIDParam ? docById : docBySlug;
  const docLoading = isUUIDParam ? idLoading : slugLoading;

  const { data: connectionsData, isLoading: connectionsLoading } = useDocumentConnections(document?.id);
  const { data: allDocs = [], isLoading: allDocsLoading } = useDocuments();

  const loading = docLoading || connectionsLoading || allDocsLoading;

  const [showBanner, setShowBanner] = useState(false);
  const [bannerDismissed, setBannerDismissed] = useState(false);

  useEffect(() => {
    if (isUUIDParam && docById && docById.slug) {
      navigate(`/evidence/${docById.slug}`, { replace: true });
    }
  }, [isUUIDParam, docById, navigate]);

  useEffect(() => {
    if (!docLoading && !document && id) {
      navigate('/evidence-list');
    }
  }, [docLoading, document, id, navigate]);

  useEffect(() => {
    if (bannerDismissed) return;
    const handleScroll = () => {
      const scrollPercent = window.scrollY / (window.document.documentElement.scrollHeight - window.innerHeight);
      if (scrollPercent > 0.5) {
        setShowBanner(true);
      }
    };
    window.addEventListener('scroll', handleScroll, { passive: true });
    return () => window.removeEventListener('scroll', handleScroll);
  }, [bannerDismissed]);

  const connections = useMemo(() => {
    if (!connectionsData) return [];
    return [
      ...connectionsData.manual.map(c => ({ ...c, isAuto: false })),
      ...connectionsData.auto.map(c => ({ ...c, isAuto: true })),
    ];
  }, [connectionsData]);

  const relatedDocs = useMemo(() => {
    if (!document || !connectionsData) return [];
    const docId = document.id;
    const relatedDocIds = new Set<string>();

    connections.forEach(conn => {
      if (conn.source_document_id === docId) relatedDocIds.add(conn.target_document_id);
      if (conn.target_document_id === docId) relatedDocIds.add(conn.source_document_id);
    });

    return allDocs.filter(d => relatedDocIds.has(d.id));
  }, [document, connectionsData, connections, allDocs]);

  const handleExportDossier = () => {
    if (!document) return;

    const dossierPackage = {
      document,
      connections,
      relatedDocuments: relatedDocs,
      exportDate: new Date().toISOString(),
    };

    const blob = new Blob([JSON.stringify(dossierPackage, null, 2)], {
      type: 'application/json',
    });
    const url = URL.createObjectURL(blob);
    const link = window.document.createElement('a');
    link.href = url;
    link.download = `dossier-${document.id}-${new Date().toISOString().split('T')[0]}.json`;
    window.document.body.appendChild(link);
    link.click();
    window.document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-black text-green-500">
        <Navigation />
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black">
          <MatrixRain />
          <div className="relative z-10 text-center">
            <div className="text-green-400 font-mono text-lg mb-2 animate-pulse">
              DECLASSIFYING [ITEM {id}]...
            </div>
          </div>
        </div>
      </div>
    );
  }

  if (!document) {
    return (
      <div className="min-h-screen bg-black text-green-500">
        <Navigation />
        <div className="container mx-auto px-6 py-20 text-center">
          <div className="text-red-400 font-mono text-lg">DOSSIER NOT FOUND</div>
          <Button
            onClick={() => navigate('/evidence-list')}
            className="mt-4 bg-green-500/20 text-green-400 hover:bg-green-500/30"
          >
            Return to Archive
          </Button>
        </div>
      </div>
    );
  }

  const tierColors = {
    verified: 'border-green-500 bg-green-500/10 text-green-400',
    open: 'border-cyan-400 bg-cyan-400/10 text-cyan-300',
    corroborated: 'border-yellow-500 bg-yellow-500/10 text-yellow-400',
    preliminary: 'border-gray-500 bg-gray-500/10 text-gray-400',
  };

  const pageUrl = `https://redpillbiblio.wtf/evidence/${document.slug}`;
  const excerpt = (document.description || document.content).substring(0, 155);

  const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
  const pillarName = document.metadata?.pillar || 'Research';
  const ogImageUrl = `${supabaseUrl}/functions/v1/generate-og-image?title=${encodeURIComponent(document.title)}&tier=${document.verification_tier}&pillar=${encodeURIComponent(pillarName)}&type=evidence`;

  const structuredData = {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: document.title,
    description: excerpt,
    datePublished: document.date_published || document.created_at,
    dateModified: document.updated_at,
    author: {
      '@type': 'Organization',
      name: 'Red Pill Bibliography Editorial Team'
    },
    publisher: {
      '@type': 'Organization',
      name: 'Red Pill Bibliography',
      logo: {
        '@type': 'ImageObject',
        url: `${window.location.origin}/logo.png`
      }
    },
    image: ogImageUrl,
    url: pageUrl,
    articleSection: pillarName,
    keywords: document.topic_tags?.join(', ') || ''
  };

  return (
    <div className="min-h-screen bg-black text-green-500">
      <SEOHead
        title={document.title}
        description={excerpt}
        url={pageUrl}
        ogImage={ogImageUrl}
        type="article"
        structuredData={structuredData}
      />

      <Navigation />

      <div className="container mx-auto px-6 py-8 pt-20 pb-24 max-w-6xl">
        <Button
          variant="ghost"
          size="sm"
          onClick={() => navigate('/evidence-list')}
          className="mb-6 text-green-400 hover:text-green-300 hover:bg-green-500/10 font-mono"
        >
          <ArrowLeft className="w-4 h-4 mr-2" />
          Back to Archive
        </Button>

        <Breadcrumb
          items={[
            { label: 'Home', href: '/' },
            { label: document.metadata?.pillar || 'Evidence', href: '/evidence-list' },
            { label: document.title },
          ]}
        />

        <div className="mb-8 bg-black border-2 border-green-500/50 rounded-lg p-6 relative overflow-hidden">
          <div className="absolute top-3 right-3 flex items-center gap-2">
            {document.verification_tier === 'verified' && (
              <div className="relative">
                <ShieldCheck className="w-8 h-8 text-yellow-500" />
                <span className="absolute -top-2 -right-2 text-[10px] font-bold text-yellow-500 rotate-12 bg-black px-1 border border-yellow-500">
                  VERIFIED
                </span>
              </div>
            )}
          </div>

          <div className="flex items-start gap-3 mb-4">
            <div className="w-10 h-10 bg-red-500/20 border border-red-500 rounded flex items-center justify-center flex-shrink-0">
              <FileText className="w-5 h-5 text-red-400" />
            </div>
            <div className="flex-1">
              <div className="text-green-500/50 font-mono text-xs mb-1">
                DOSSIER ID: {document.id.substring(0, 8).toUpperCase()}
              </div>
              <h1 className="text-2xl font-bold text-green-300 leading-tight">
                {document.title}
              </h1>
            </div>
          </div>

          <p className="text-green-400/80 text-sm mb-4 leading-relaxed">
            {document.description}
          </p>

          <div className="flex flex-wrap gap-3 mb-4">
            <Badge className={`${tierColors[document.verification_tier]} font-mono text-xs uppercase`}>
              <Shield className="w-3 h-3 mr-1" />
              {document.verification_tier === 'corroborated' ? 'VALID' : document.verification_tier}
            </Badge>
            <Badge className="bg-green-500/20 text-green-400 border-green-500/30 font-mono text-xs">
              <FileText className="w-3 h-3 mr-1" />
              {document.document_type}
            </Badge>
            {(() => {
              const formatted = formatUTCDateShort(document.date_published);
              return formatted ? (
                <Badge className="bg-green-500/20 text-green-400 border-green-500/30 font-mono text-xs">
                  <Calendar className="w-3 h-3 mr-1" />
                  {formatted}
                </Badge>
              ) : (
                <Badge className="bg-green-500/20 text-green-400 border-green-500/30 font-mono text-xs italic">
                  <Calendar className="w-3 h-3 mr-1" />
                  Date Unknown
                </Badge>
              );
            })()}
          </div>

          <div className="flex flex-col gap-4">
            <div className="flex flex-col sm:flex-row gap-3 items-start sm:items-center flex-wrap">
              {document.source_url && (
                <div className="flex items-center gap-2 w-full sm:w-auto">
                  <Button
                    asChild
                    className="bg-green-500/20 text-green-400 border border-green-500/50 hover:bg-green-500/30 font-mono flex-1 sm:flex-initial"
                  >
                    <a href={document.source_url} target="_blank" rel="noopener noreferrer">
                      <ExternalLink className="w-4 h-4 mr-2" />
                      ORIGINAL SOURCE
                    </a>
                  </Button>
                  {document.verification_tier === 'verified' && document.has_mirror && (
                    <Badge className="bg-cyan-500/20 text-cyan-400 border-cyan-500/50 font-mono text-[10px] px-2 py-1">
                      <Archive className="w-3 h-3 mr-1" />
                      Mirrored Copy
                    </Badge>
                  )}
                  {!document.has_mirror && (
                    <Badge className="bg-yellow-500/10 text-yellow-500/80 border-yellow-500/30 font-mono text-[10px] px-2 py-1">
                      <AlertTriangle className="w-3 h-3 mr-1" />
                      External Link
                    </Badge>
                  )}
                </div>
              )}
              <Button
                onClick={handleExportDossier}
                variant="outline"
                className="border-green-500/50 text-green-400 hover:bg-green-500/10 font-mono w-full sm:w-auto"
              >
                <Download className="w-4 h-4 mr-2" />
                EXPORT DOSSIER PACKAGE
              </Button>
            </div>
            <div className="flex items-center justify-between">
              <SocialShare
                title={document.title}
                url={window.location.href}
              />
              <ReportBrokenLink documentId={document.id} />
            </div>
          </div>
        </div>

        <div className="mb-8 bg-black border border-green-500/30 rounded-lg p-6">
          <h2 className="text-green-400 font-mono text-sm font-bold mb-4 flex items-center gap-2">
            <FileText className="w-4 h-4" />
            FULL EXCERPT
          </h2>
          <EpistemicLegend />
          <div className="bg-green-500/5 border border-green-500/20 rounded p-4 font-mono text-sm text-green-300/80 leading-relaxed whitespace-pre-wrap max-h-96 overflow-y-auto">
            {document.content || document.description}
            {renderLabeledClaims(document.labeled_claims)}
          </div>
        </div>

        <ContextAndResponse document={document} />

        <div className="mb-8 bg-black border border-green-500/30 rounded-lg p-6">
          <h2 className="text-green-400 font-mono text-sm font-bold mb-4 flex items-center gap-2">
            <Calendar className="w-4 h-4" />
            CHAIN OF CUSTODY
          </h2>
          <div className="space-y-3">
            <div className="flex items-start gap-3 pl-4 border-l-2 border-green-500/30">
              <div className="text-green-500/50 font-mono text-xs w-32">
                {formatUTCDateShort(document.date_published) || <span className="italic">Date Unknown</span>}
              </div>
              <div className="flex-1">
                <div className="text-green-300 font-mono text-xs font-bold">RELEASE DATE</div>
                <div className="text-green-500/70 font-mono text-xs mt-1">
                  Document published/released
                </div>
              </div>
            </div>
            {document.created_at && (
              <div className="flex items-start gap-3 pl-4 border-l-2 border-green-500/30">
                <div className="text-green-500/50 font-mono text-xs w-32">
                  {formatUTCDateShort(document.created_at)}
                </div>
                <div className="flex-1">
                  <div className="text-green-300 font-mono text-xs font-bold">CATALOGUED</div>
                  <div className="text-green-500/70 font-mono text-xs mt-1">
                    Added to evidence archive
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>

        {relatedDocs.length > 0 && (
          <div className="mb-8 bg-black border border-green-500/30 rounded-lg p-6">
            <h2 className="text-green-400 font-mono text-sm font-bold mb-4 flex items-center gap-2">
              <Network className="w-4 h-4" />
              RELATED ITEMS ({relatedDocs.length})
            </h2>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {relatedDocs.map(relatedDoc => (
                <button
                  key={relatedDoc.id}
                  onClick={() => navigate(`/evidence/${relatedDoc.slug}`)}
                  className="bg-green-500/5 border border-green-500/30 rounded p-3 text-left hover:bg-green-500/10 hover:border-green-500/50 transition-all"
                >
                  <div className="text-green-300 font-mono text-xs font-bold mb-1 line-clamp-2">
                    {relatedDoc.title}
                  </div>
                  <div className="text-green-500/50 font-mono text-[10px]">
                    {relatedDoc.document_type}
                  </div>
                </button>
              ))}
            </div>
          </div>
        )}

        {document.notes && document.notes.length > 0 && (
          <div className="bg-yellow-500/10 border border-yellow-500/30 rounded-lg p-6 font-mono text-xs text-yellow-300/90">
            <div className="font-bold mb-2">NOTES:</div>
            {document.notes}
          </div>
        )}
      </div>

      {showBanner && !bannerDismissed && (
        <NewsletterSignup
          variant="banner"
          onDismiss={() => {
            setBannerDismissed(true);
            setShowBanner(false);
          }}
        />
      )}

      <Footer />
    </div>
  );
}
