/*
  # Add 12 New Enemies of Truth Records — April 2026 Batch

  1. New Entries
    - YOAV GALLANT — ICC arrest warrant (Nov 2024), war crimes + crimes against humanity in Gaza
    - OMAR AL-BASHIR — ICC warrants since 2009, genocide + crimes against humanity in Darfur
    - JOSEPH KONY — ICC fugitive since 2005, 39 confirmed charges, historic in absentia trial 2025
    - NICOLÁS MADURO — Active ICC investigation, first Americas case, possible sealed warrant
    - BASHAR AL-ASSAD — Active French arrest warrant (Jan 2025), OPCW-confirmed chemical weapons
    - XI JINPING — ICC complaint for Uyghur genocide, U.S. genocide designation 2021
    - MOHAMMED BIN SALMAN — ODNI-confirmed Khashoggi murder approval, Yemen war crimes
    - KIM JONG-UN — UN found crimes against humanity 2014, IBA found 10/11 Rome Statute crimes 2022
    - MIN AUNG HLAING — ICC arrest warrant application pending (Nov 2024), UN genocidal intent finding 2018
    - MARIA ALEKSEYEVNA LVOVA-BELOVA — ICC arrest warrant active (Mar 2023), co-accused with Putin
    - DR. ANTHONY FAUCI — DOJ criminal referrals for perjury, autopen pardon constitutionality disputed
    - KLAUS SCHWAB — Resigned April 2025 under WEF whistleblower investigation

  2. Notes
    - All records use ON CONFLICT DO NOTHING for idempotency
    - sort_order and footer_note set to NULL for all records
    - JSONB fields (key_facts, status_tags, sources) passed as properly typed JSON
*/

INSERT INTO enemies_of_truth (name, title, subtitle, severity, summary, key_facts, status_tags, evidence_documented, sources, footer_note, sort_order)
VALUES
(
  'YOAV GALLANT',
  'Minister of Defence of Israel (2022–November 2024)',
  'ICC Arrest Warrant Active — War Crime of Starvation + Crimes Against Humanity in Gaza',
  'CRITICAL',
  'Yoav Gallant served as Israel''s Minister of Defence from December 2022 until his dismissal on November 5, 2024. On November 21, 2024, the International Criminal Court issued an arrest warrant for Gallant — the same day as the warrant for Netanyahu — for his alleged criminal responsibility for war crimes and crimes against humanity committed in the Gaza Strip from at least October 8, 2023 through at least May 20, 2024. ICC Pre-Trial Chamber I found reasonable grounds to believe Gallant bears criminal responsibility as co-perpetrator and civilian superior for the war crime of starvation as a method of warfare, intentionally directing attacks against the civilian population, and the crimes against humanity of murder, persecution, and other inhumane acts. As of April 2026, the warrant remains active and unexecuted. All 124 ICC member states are legally obligated to arrest him upon entry to their territory.',
  '["ICC arrest warrant issued November 21, 2024 by Pre-Trial Chamber I — simultaneously with the warrant for Netanyahu","Charged with: war crime of starvation as a method of warfare (Article 8(2)(b)(xxv)); war crime of intentionally directing attacks against the civilian population; crimes against humanity of murder, persecution, and other inhumane acts","ICC judges found he bore criminal responsibility as co-perpetrator and as a civilian superior who failed to prevent crimes by subordinates","Israel rejected ICC jurisdiction and challenged the warrant; Pre-Trial Chamber I unanimously rejected both jurisdictional challenges under Articles 18 and 19 of the Rome Statute","As of April 2026, the warrant remains outstanding — Gallant has not been arrested or transferred to The Hague","Dismissed as Defense Minister by Netanyahu on November 5, 2024 — sixteen days before the warrant was issued"]'::jsonb,
  '["ICC ARREST WARRANT ACTIVE","NO ARREST","CO-PERPETRATOR WITH NETANYAHU","124 STATES LEGALLY OBLIGATED TO ARREST"]'::jsonb,
  'ICC Pre-Trial Chamber I arrest warrant issued November 21, 2024 (simultaneously with Netanyahu warrant) for war crimes and crimes against humanity in Gaza. Charges: war crime of starvation as a method of warfare under Article 8(2)(b)(xxv) of the Rome Statute; war crime of intentionally directing attacks against the civilian population; crimes against humanity of murder, persecution, and other inhumane acts. ICC found Gallant criminally responsible as both direct co-perpetrator and civilian superior. Israel challenged ICC jurisdiction under Articles 18 and 19; Pre-Trial Chamber I unanimously rejected both challenges. Gallant was dismissed as Defense Minister by Netanyahu on November 5, 2024 — 16 days before the warrant. As of April 2026, the warrant is active; no arrest has been made.',
  '[{"url":"https://www.icc-cpi.int/defendant/gallant","date":"2024-11-21","name":"ICC Official — Gallant Defendant Page"},{"url":"https://news.un.org/en/story/2024/11/1157286","date":"2024-11-20","name":"UN News — ICC Issues Arrest Warrants for Netanyahu and Gallant"},{"url":"https://coalitionfortheicc.org/news/icc-judges-issue-three-arrest-warrants-palestine-situation","date":"2024-12-15","name":"Coalition for the ICC — Three Arrest Warrants Issued in Palestine Situation"},{"url":"https://www.amnesty.org/en/latest/news/2024/11/israel-opt-netanyahu-gallant-and-al-masri-must-face-justice-at-the-icc-for-charges-of-crimes-against-humanity-and-war-crimes/","date":"2024-11-20","name":"Amnesty International — Netanyahu, Gallant Must Face Justice at the ICC"}]'::jsonb,
  NULL,
  NULL
),
(
  'OMAR AL-BASHIR',
  'Former President of Sudan (1989–2019)',
  'ICC Arrest Warrants for Genocide, War Crimes & Crimes Against Humanity — Darfur — Outstanding Since 2009',
  'CRITICAL',
  'Omar al-Bashir ruled Sudan for 30 years before being deposed in a military coup in April 2019. He is the subject of two ICC arrest warrants — the first ever issued against a sitting head of state. The first warrant, issued March 4, 2009, charged him with five counts of crimes against humanity and two counts of war crimes for his role in orchestrating systematic violence in Darfur beginning in 2003. A second warrant, issued July 12, 2010, added three counts of genocide — marking the ICC''s first-ever genocide charges — for the systematic killing, serious bodily harm, and deliberately inflicted conditions of destruction against the Fur, Masalit, and Zaghawa ethnic groups. The UN estimates 300,000 people were killed and 2.7 million displaced in Darfur. Despite his 2019 ouster and ongoing domestic detention in Sudan on separate charges, al-Bashir has never been transferred to The Hague. As of April 2026, both ICC warrants remain unexecuted.',
  '["First ICC arrest warrant issued March 4, 2009 — the first-ever against a sitting head of state — for five counts of crimes against humanity (murder, extermination, forcible transfer, torture, rape) and two counts of war crimes","Second ICC arrest warrant issued July 12, 2010 — the first genocide charges in ICC history — for three counts of genocide against the Fur, Masalit, and Zaghawa ethnic groups","UN estimates 300,000 killed and 2.7 million displaced in Darfur conflict since 2003","Deposed in military coup April 2019; held in Sudanese custody on domestic charges but has never been transferred to the ICC","Multiple countries including Kenya, Chad, Djibouti, Malawi, and South Africa allowed al-Bashir to visit without executing the arrest warrant; ICC Pre-Trial Chambers reported their non-cooperation to the UN Security Council","As of April 2026, the ICC warrants are the longest-outstanding unexecuted arrest warrants for a former head of state in the Court''s history"]'::jsonb,
  '["ICC WARRANT ACTIVE SINCE 2009","GENOCIDE CHARGES","NEVER TRANSFERRED TO THE HAGUE","DOMESTIC CUSTODY SUDAN","LONGEST-OUTSTANDING ICC WARRANT"]'::jsonb,
  'Two ICC arrest warrants: ICC-02/05-01/09-1 (March 4, 2009) for five counts of crimes against humanity and two counts of war crimes in Darfur; and a second warrant (July 12, 2010) adding three counts of genocide against the Fur, Masalit, and Zaghawa ethnic groups — the first genocide charges issued by the ICC. UN estimates 300,000 killed and 2.7 million displaced. ICC Pre-Trial Chambers have reported non-compliance by multiple states to the UN Security Council after al-Bashir visited their territories without arrest. Al-Bashir was deposed in April 2019 and remains in Sudanese custody on domestic charges; Sudan has not transferred him to The Hague despite ICC requests. Warrants remain the longest-outstanding unexecuted ICC warrants for a head of state.',
  '[{"url":"https://www.icc-cpi.int/darfur/albashir","date":"2010-07-12","name":"ICC Official — Al Bashir Case Page (ICC-02/05-01/09)"},{"url":"https://news.un.org/en/story/2010/07/344502","date":"2010-07-12","name":"UN News — ICC Charges Sudanese President with Genocide"},{"url":"https://www.ushmm.org/genocide-prevention/blog/icc-issues-arrest-warrant-for-sudanese-president-bashir","date":"2009-03-04","name":"USHMM — ICC Issues Arrest Warrant for Sudanese President Bashir"},{"url":"https://www.hrw.org/news/2010/07/13/sudan-icc-warrant-al-bashir-genocide","date":"2010-07-13","name":"HRW — Sudan: ICC Warrant for Al-Bashir on Genocide"},{"url":"https://www.coalitionfortheicc.org/cases/omar-albashir","date":"2024-01-01","name":"Coalition for the ICC — Omar al-Bashir Case Overview"}]'::jsonb,
  NULL,
  NULL
),
(
  'JOSEPH KONY',
  'Founder & Commander-in-Chief, Lord''s Resistance Army (LRA)',
  'ICC''s Longest-Standing Fugitive Since 2005 — 39 Counts War Crimes & Crimes Against Humanity — Historic In Absentia Trial Commenced 2025',
  'CRITICAL',
  'Joseph Kony founded the Lord''s Resistance Army in Uganda in 1987, waging a campaign of mass atrocity across northern Uganda, the DRC, Central African Republic, and South Sudan for nearly two decades. The ICC issued its first arrest warrant for Kony on July 8, 2005 — making him one of the Court''s original targets and its longest-standing fugitive. The warrant covers 39 counts of war crimes and crimes against humanity, including murder, enslavement, sexual slavery, forced marriage, use of child soldiers, torture, and forced pregnancy. The LRA killed over 100,000 civilians, abducted between 60,000 and 100,000 children, and displaced 2.5 million people. In a historic first for international law, ICC Pre-Trial Chamber III confirmed all 39 charges against Kony in absentia on November 6, 2025 — the first-ever ICC case to proceed without the accused present. Kony remains at large as of April 2026.',
  '["Original ICC arrest warrant issued July 8, 2005 — amended September 27, 2005 (ICC-02/04-01/05-53) — making Kony the ICC''s longest-standing fugitive at over 20 years","39 confirmed counts: crimes against humanity (murder, enslavement, sexual slavery, rape, forced marriage, persecution, other inhumane acts) and war crimes (murder, cruel treatment, attacking civilians, pillaging, child soldiers, outrages against personal dignity)","LRA killed over 100,000 civilians; abducted 60,000–100,000 children; displaced 2.5 million people across Uganda, DRC, Central African Republic, and South Sudan","November 6, 2025: Pre-Trial Chamber III confirmed all 39 charges against Kony in absentia — the first-ever ICC in absentia trial proceeding in the Court''s history","Kony''s whereabouts unknown; believed to be hiding in remote Central African Republic border regions with a small remnant of the LRA","ICC in absentia proceedings create a full evidentiary record for potential future prosecution if Kony is ever apprehended"]'::jsonb,
  '["ICC FUGITIVE SINCE 2005","39 CONFIRMED CHARGES","IN ABSENTIA TRIAL — HISTORIC FIRST 2025","AT LARGE"]'::jsonb,
  'ICC arrest warrant ICC-02/04-01/05-53, issued July 8, 2005 and amended September 27, 2005, covering 39 counts of war crimes and crimes against humanity committed across Uganda, DRC, CAR, and South Sudan. Documented atrocities include mass killings, enslavement, sexual slavery, child soldier recruitment, and forced displacement of 2.5 million people. On November 6, 2025, ICC Pre-Trial Chamber III confirmed all 39 charges against Kony in absentia — the first in absentia charge confirmation in ICC history, establishing a full evidentiary record. Kony remains at large. Evidence assembled from hundreds of witness testimonies, satellite imagery, and corroborating documentation gathered over 20 years.',
  '[{"url":"https://www.icc-cpi.int/court-record/icc-02/04-01/05-53","date":"2005-07-08","name":"ICC Official — Warrant of Arrest for Joseph Kony (ICC-02/04-01/05-53)"},{"url":"https://www.gicj.org/positions-opinons/gicj-positions-and-opinions/4334-the-prosecutor-v-joseph-kony-icc","date":"2025-12-17","name":"GICJ — The Prosecutor v. Joseph Kony: Charges Confirmed In Absentia"},{"url":"https://www.amnesty.org/ar/wp-content/uploads/2021/08/afr590082005en.pdf","date":"2005-10-14","name":"Amnesty International — Uganda: First Ever ICC Arrest Warrants"}]'::jsonb,
  NULL,
  NULL
),
(
  'NICOLÁS MADURO',
  'President of Venezuela (2013–Present)',
  'Active ICC Investigation for Crimes Against Humanity — Possible Sealed Arrest Warrant — Venezuela Withdrawing from ICC',
  'CRITICAL',
  'Nicolás Maduro has presided over a documented decade-long campaign of systematic state repression in Venezuela. The ICC opened a formal investigation on November 3, 2021 — the first ICC investigation into a country in the Americas — for crimes against humanity including arbitrary detention, torture, sexual violence, rape, and the murder of political opponents and protesters. Venezuela attempted to defer the investigation by claiming it was conducting its own proceedings; the ICC Appeals Chamber unanimously rejected this in March 2024, finding Venezuela''s domestic efforts insufficient. By late 2025, the ICC Office of the Prosecutor concluded that ''no meaningful progress'' had been made and closed its in-country presence. In November 2025, the ICC amended its regulations to seal all new arrest warrants initially, raising the possibility that a warrant for Maduro may already exist but has not been made public. Venezuela''s National Assembly voted unanimously in December 2025 to begin withdrawing from the Rome Statute.',
  '["ICC preliminary examination opened 2018; full investigation announced November 3, 2021 — first-ever ICC investigation in the Americas","Six states (Argentina, Canada, Colombia, Chile, Paraguay, Peru) referred Venezuela to the ICC in September 2018 under Article 14 of the Rome Statute","ICC investigation covers crimes against humanity committed since at least April 2017: arbitrary detention, torture, sexual violence, murder of political protesters, enforced disappearances","UN Human Rights Council Fact-Finding Mission documented 124 protesters killed and 5,000+ detained during 2017 demonstrations alone","March 1, 2024: ICC Appeals Chamber unanimously rejected Venezuela''s deferral appeal; full investigation resumed","October 2025: ICC OTP concluded Venezuela made ''no meaningful progress'' on domestic accountability; closed in-country presence December 2025","November 2025: ICC amended regulations to seal all new arrest warrants initially — a warrant for Maduro may already exist and not yet be public","December 11, 2025: Venezuela''s National Assembly voted to annul the Rome Statute confirmation law, initiating ICC withdrawal"]'::jsonb,
  '["ACTIVE ICC INVESTIGATION","POSSIBLE SEALED ARREST WARRANT","VENEZUELA WITHDRAWING FROM ICC","DECADE OF DOCUMENTED REPRESSION","FIRST ICC AMERICAS INVESTIGATION"]'::jsonb,
  'ICC investigation opened November 3, 2021 (ICC-02/18) following Article 14 referral by six states. Charges under investigation: crimes against humanity of arbitrary detention, torture, sexual violence, murder, and enforced disappearances committed from at least April 2017. UN HRC Fact-Finding Mission documented 124 protesters killed and 5,000+ detained in 2017 alone. ICC Appeals Chamber unanimously rejected Venezuela''s deferral argument (March 1, 2024). ICC OTP Annual Report 2025 concludes ''no meaningful progress'' by national authorities; in-country presence closed December 2025. ICC November 2025 rule change to seal new warrants means Maduro warrant status cannot be confirmed publicly. Venezuela voted to withdraw from Rome Statute December 11, 2025.',
  '[{"url":"https://www.icc-cpi.int/venezuela-i","date":"2021-11-03","name":"ICC Official — Venezuela I Situation Page"},{"url":"https://www.humanrightscentre.org/blog/moving-forward-icc-upholds-investigation-venezuela","date":"2024-06-15","name":"Human Rights Centre — ICC Upholds Venezuela Investigation (Appeals Chamber Decision)"},{"url":"https://reliefweb.int/report/venezuela-bolivarian-republic/venezuela-icc-prosecutor-s-primary-consideration-opening","date":"2021-11-04","name":"ICC Prosecutor — Primary Consideration in Opening Venezuela Investigation"},{"url":"https://justiceinconflict.org/2026/01/05/the-icc-trump-and-venezuela-the-catch-22-of-who-prosecutes-nicolas-maduro/","date":"2026-01-05","name":"Justice in Conflict — ICC, Trump, and Venezuela: The Catch-22 over Who Prosecutes Maduro"},{"url":"https://www.reuters.com/world/americas/venezuelan-lawmakers-pave-way-withdrawal-international-criminal-court-2025-12-11/","date":"2025-12-11","name":"Reuters — Venezuelan Lawmakers Pave Way for ICC Withdrawal"}]'::jsonb,
  NULL,
  NULL
),
(
  'BASHAR AL-ASSAD',
  'Former President of Syria (2000–December 2024)',
  'Active French Arrest Warrant (Jan 2025) — Chemical Weapons Deaths 1,000+ Civilians — In Exile in Russia',
  'CRITICAL',
  'Bashar al-Assad ruled Syria as a totalitarian dictator until rebel forces seized Damascus in December 2024, when he fled to Russia. Under his command, Syrian government forces conducted a systematic campaign including the August 2013 sarin attack in Eastern Ghouta — confirmed by the UN and OPCW — that killed an estimated 1,000–1,500 people. UN reports documented systematic torture, extermination, forced disappearances, and massacres constituting crimes against humanity throughout the civil war. French investigating judges issued an arrest warrant for Assad in November 2023 for the Ghouta chemical attacks; France''s Cour de Cassation annulled that specific warrant on July 25, 2025, citing head-of-state personal immunity for acts committed while in office. However, a second arrest warrant — issued January 20, 2025, after Assad was already out of power — for ordering deadly barrel bombings in Daraa in 2017 that killed a French civilian remains fully in force. As of April 2026, Assad lives in Russian exile, protected from extradition.',
  '["August 21, 2013: Syrian Air Force launched sarin gas attack on Eastern Ghouta — confirmed by UN investigators and OPCW-UN Joint Investigative Mechanism; killed an estimated 1,000–1,500 civilians including children","OPCW-UN Joint Investigative Mechanism confirmed Syrian government responsibility for multiple chemical weapons attacks including Ghouta and Khan Shaykhun (2017)","UN Commission of Inquiry documented systematic crimes against humanity by Assad government: torture, extermination, forced disappearances, massacres, sexual violence","November 14, 2023: French magistrate judges issued arrest warrant for Assad for complicity in crimes against humanity and war crimes related to the 2013 Ghouta sarin attack","July 25, 2025: France''s Cour de Cassation annulled the November 2023 warrant on grounds of head-of-state personal immunity for acts committed while Assad held office","January 20, 2025: A SECOND French arrest warrant was issued (while Assad was already out of power) for complicity in war crimes for the 2017 barrel bombing of Daraa that killed a French civilian — this warrant REMAINS IN FORCE","Assad fled Syria to Russia in December 2024 following fall of his regime; Russia provides refuge and blocks extradition","May 2025: Syria''s transitional government established the National Commission for Transitional Justice — no trials of Assad regime officials have commenced as of April 2026"]'::jsonb,
  '["SECOND FRENCH ARREST WARRANT ACTIVE (JAN 2025)","FIRST WARRANT ANNULLED ON IMMUNITY GROUNDS (JUL 2025)","IN EXILE RUSSIA","OPCW-CONFIRMED CHEMICAL WEAPONS","ZERO EXTRADITION PROSPECT"]'::jsonb,
  'OPCW-UN Joint Investigative Mechanism confirmed Syrian government responsibility for sarin attack on Eastern Ghouta (August 21, 2013) killing 1,000–1,500 civilians, and for Khan Shaykhun sarin attack (April 2017). UN Commission of Inquiry documented crimes against humanity including systematic torture, extermination, forced disappearances, and rape. French arrest warrant (Nov 14, 2023) for Assad for Ghouta chemical weapons complicity: upheld by Paris Court of Appeal (June 26, 2024); annulled by Cour de Cassation (July 25, 2025) on personal head-of-state immunity grounds. Second French arrest warrant issued January 20, 2025 — after Assad left power — for 2017 Daraa barrel bombing killing a French civilian: this warrant remains in force. Assad in Russian exile since December 2024; no extradition possible.',
  '[{"url":"https://www.jurist.org/news/2025/07/france-court-overturns-arrest-warrant-against-former-syria-president-bashar-al-assad/","date":"2025-07-27","name":"JURIST — France Court Overturns 2023 Assad Warrant; Second 2025 Warrant Remains Active"},{"url":"http://www.courdecassation.fr/en/toutes-les-actualites/2025/07/25/press-release-scope-immunity-foreign-officials-and-heads-state","date":"2025-07-25","name":"Cour de Cassation — Press Release: Scope of Immunity of Foreign Officials and Heads of State"},{"url":"https://www.reuters.com/world/french-court-upholds-warrant-syrias-assad-over-chemical-weapons-2024-06-26/","date":"2024-06-26","name":"Reuters — French Court Upholds Assad Warrant Over Chemical Weapons (June 2024)"},{"url":"https://www.hrw.org/world-report/2025/country-chapters/syria","date":"2024-12-18","name":"HRW — World Report 2025: Syria"},{"url":"https://en.wikipedia.org/wiki/Prosecution_of_Syrian_civil_war_criminals","date":"2025-01-21","name":"Wikipedia — Prosecution of Syrian Civil War Criminals (Second Warrant, Jan 2025)"}]'::jsonb,
  NULL,
  NULL
),
(
  'XI JINPING',
  'General Secretary, Chinese Communist Party / President of the People''s Republic of China',
  'ICC Complaint Filed for Genocide & Crimes Against Humanity Against Uyghurs — No ICC Jurisdiction — No Criminal Accountability',
  'CRITICAL',
  'Xi Jinping personally issued secret directives ordering Chinese security forces to show ''absolutely no mercy'' against Uyghur and other Turkic Muslim peoples in Xinjiang — reported by the New York Times in 2019 via leaked internal CCP documents. Under his command, China constructed the largest mass detention system since the Holocaust, incarcerating an estimated 1–1.8 million Uyghurs in ''re-education'' camps, subjecting them to systematic torture, forced labor, forced sterilization, sexual violence, family separation, and cultural erasure. Amnesty International''s 2021 report concluded these acts constitute crimes against humanity. The independent Uyghur Tribunal concluded in 2021 that China committed both crimes against humanity and genocide. The U.S. government officially designated these acts as genocide in January 2021. In July 2020, the East Turkistan Government in Exile filed an ICC complaint against Xi Jinping and over 30 senior Chinese officials. Because China is not a Rome Statute party and holds a UN Security Council veto, no accountability mechanism has been initiated as of April 2026.',
  '["2014: Xi Jinping issued secret ''absolutely no mercy'' directives targeting Uyghurs; reported via leaked internal CCP documents published by the New York Times, November 2019","Estimated 1–1.8 million Uyghurs detained in ''Vocational Skills Education and Training Centers'' — documented by UN OHCHR, Amnesty International, HRW, and ASPI satellite imagery analysis","Amnesty International 2021 report: China''s treatment of Uyghurs constitutes crimes against humanity under the Rome Statute","Uyghur Tribunal (independent panel chaired by Sir Geoffrey Nice QC, 2021): China perpetrated torture, crimes against humanity, and genocide against Uyghur people","U.S. government formally designated China''s treatment of Uyghurs as genocide — January 19, 2021 (Pompeo) and reaffirmed January 20, 2021 (Blinken)","July 6, 2020: East Turkistan Government in Exile and East Turkistan National Awakening Movement filed ICC complaint against Xi Jinping and 30+ officials for genocide and crimes against humanity","ICC complaint invoked jurisdiction through documented forcible deportation of Uyghurs from ICC member states Tajikistan and Kyrgyzstan back to China","63 parliamentarians from 16 countries formally backed the ICC complaint","China''s UN Security Council permanent seat effectively blocks any referral to the ICC"]'::jsonb,
  '["ICC COMPLAINT FILED 2020","NO ICC JURISDICTION","U.S. GENOCIDE DESIGNATION 2021","AMNESTY CRIMES AGAINST HUMANITY FINDING","UYGHUR TRIBUNAL GENOCIDE FINDING","ZERO ACCOUNTABILITY"]'::jsonb,
  'Leaked CCP internal documents (New York Times, November 2019) containing Xi Jinping''s ''absolutely no mercy'' directives against Uyghurs, 2014. UN OHCHR August 2022 assessment: ''serious human rights violations in the Uyghur region may constitute international crimes, in particular crimes against humanity.'' Amnesty International 2021: ''break their lineage, break their roots'' — China''s campaign constitutes crimes against humanity. Uyghur Tribunal (Sir Geoffrey Nice QC, 2021): genocide and crimes against humanity findings. U.S. State Department genocide determination (January 2021). ICC complaint filed July 2020 by ETGE and ETNM against Xi and 30+ officials; ICC cannot exercise direct jurisdiction as China is not a Rome Statute party; complaint argued jurisdiction via deportations from ICC member states Tajikistan and Kyrgyzstan.',
  '[{"url":"https://www.amnesty.org/en/latest/news/2025/08/china-still-no-accountability-for-crimes-against-humanity-in-xinjiang-three-years/","date":"2025-08-31","name":"Amnesty International — China: Still No Accountability for Crimes Against Humanity in Xinjiang"},{"url":"https://www.hrw.org/report/2021/04/19/break-their-lineage-break-their-roots/chinas-crimes-against-humanity-targeting","date":"2021-04-19","name":"HRW — Break Their Lineage, Break Their Roots: China''s Crimes Against Humanity Targeting Uyghurs"},{"url":"https://www.lawfaremedia.org/article/unpacking-recent-uighur-icc-complaint-against-chinese-leaders","date":"2023-01-17","name":"Lawfare — Unpacking the Uyghur ICC Complaint Against Chinese Leaders"},{"url":"https://www.humanrightsresearch.org/post/persecution-of-uyghurs-in-xinjiang-torture-crimes-against-humanity-and-genocide","date":"2026-01-20","name":"Human Rights Research — Persecution of Uyghurs: Torture, Crimes Against Humanity and Genocide"},{"url":"https://east-turkistan.net/east-turkistanis-demand-xi-jinpings-arrest-after-icc-issues-putin-warrant/","date":"2023-03-17","name":"East Turkistan Government in Exile — Demand for Xi Jinping''s Arrest"}]'::jsonb,
  NULL,
  NULL
),
(
  'MOHAMMED BIN SALMAN',
  'Crown Prince & Prime Minister of Saudi Arabia / De Facto Ruler',
  'ODNI-Confirmed Orchestrator of Jamal Khashoggi Murder — Yemen War Crimes Documented — Zero Criminal Accountability',
  'CRITICAL',
  'Mohammed bin Salman is the de facto ruler of Saudi Arabia and one of the most powerful heads of government to have been directly implicated in premeditated murder by U.S. intelligence, yet never face any criminal proceedings. On February 26, 2021, the U.S. Office of the Director of National Intelligence publicly released its declassified assessment concluding that ''Saudi Arabia''s Crown Prince Muhammad bin Salman approved an operation in Istanbul, Turkey to capture or kill Saudi journalist Jamal Khashoggi.'' Khashoggi — a Washington Post columnist and U.S. resident — was lured to the Saudi consulate in Istanbul on October 2, 2018, where he was murdered and dismembered by a 15-member Saudi hit squad. The UN Special Rapporteur independently concluded it was ''a deliberate, premeditated execution, an extrajudicial killing for which the state of Saudi Arabia is responsible,'' with credible evidence linking MBS directly. As Defence Minister since 2015, MBS has also presided over the Saudi-led coalition''s military campaign in Yemen, documented by UN investigators as constituting war crimes and crimes against humanity. No criminal charges have ever been filed against MBS anywhere in the world.',
  '["October 2, 2018: Jamal Khashoggi murdered inside Saudi consulate in Istanbul by a 15-member Saudi Rapid Intervention Force operating directly under MBS''s command and protective detail","February 26, 2021: ODNI declassified assessment directly states MBS ''approved an operation to capture or kill'' Khashoggi, based on his control of decision making and direct involvement of his personal protective detail","UN Special Rapporteur Agnes Callamard (June 2019): Khashoggi''s murder was ''a deliberate, premeditated execution'' and ''an extrajudicial killing for which the state of Saudi Arabia is responsible'' with credible evidence linking MBS","U.S. Treasury sanctioned Saudi Arabia''s former deputy head of general intelligence and the Rapid Intervention Force, and issued 76 ''Khashoggi Ban'' visa restrictions — but MBS himself was never directly sanctioned","Since 2015, MBS-commanded Saudi coalition airstrikes in Yemen have targeted hospitals, schools, weddings, and civilian infrastructure — UN investigators documented these as war crimes","UN estimates 10,000+ civilians killed by Saudi-led coalition airstrikes in Yemen; blockade-induced famine affected millions","U.S. Senate passed resolution December 2018 holding MBS accountable for Khashoggi murder and Yemen humanitarian crisis — not enacted into law","No criminal charges filed against MBS in any jurisdiction as of April 2026; protected by Saudi sovereignty and U.S.-Saudi strategic relations"]'::jsonb,
  '["ODNI-CONFIRMED MURDER APPROVAL","NO CRIMINAL CHARGES","YEMEN WAR CRIMES DOCUMENTED","UN EXTRAJUDICIAL KILLING FINDING","GEOPOLITICAL IMMUNITY"]'::jsonb,
  'ODNI declassified assessment (February 26, 2021): ''We assess that Saudi Arabia''s Crown Prince Muhammad bin Salman approved an operation in Istanbul, Turkey to capture or kill Saudi journalist Jamal Khashoggi.'' Assessment based on MBS''s ''control of decision-making in the Kingdom'' and ''direct involvement of a key adviser and members of [MBS''s] protective detail.'' UN Special Rapporteur Agnes Callamard report (June 2019): Khashoggi murder was ''a deliberate, premeditated execution'' with ''credible evidence'' linking MBS. U.S. Senate resolution (December 2018) holding MBS accountable for Khashoggi and Yemen. UN Yemen Panel of Experts reports documenting Saudi coalition airstrikes on civilian infrastructure as war crimes. No criminal prosecution in any jurisdiction as of April 2026.',
  '[{"url":"https://www.dni.gov/files/ODNI/documents/assessments/Assessment-Saudi-Gov-Role-in-JK-Death-20210226v2.pdf","date":"2021-02-26","name":"ODNI — Assessing the Saudi Government''s Role in the Killing of Jamal Khashoggi (Declassified)"},{"url":"https://www.pbs.org/wgbh/frontline/article/saudi-crown-prince-approved-plan-to-capture-or-kill-jamal-khashoggi-according-to-declassified-report/","date":"2021-02-26","name":"PBS Frontline — Saudi Crown Prince Approved Capture or Kill Plan"},{"url":"https://www.aljazeera.com/news/2021/2/26/mbs-oversaw-saudi-killers-of-khashoggi-us-intel-report","date":"2021-02-26","name":"Al Jazeera — MBS Approved Operation to Capture or Kill Khashoggi"},{"url":"https://www.ecdhr.org/saudi-arabia-the-un-report-on-khashoggi-claims-there-is-credible-evidence-linking-prince-mohammed-bin-salman/","date":"2019-06-19","name":"ECDHR — UN Report: Credible Evidence Linking MBS to Khashoggi Murder"},{"url":"https://www.lgraham.senate.gov/public/index.cfm/2018/12/senate-measure-holds-saudi-crown-prince-accountable-for-killing-of-jamal-khashoggi","date":"2018-12-04","name":"U.S. Senate — Resolution Holding MBS Accountable for Khashoggi and Yemen"}]'::jsonb,
  NULL,
  NULL
),
(
  'KIM JONG-UN',
  'Supreme Leader, Democratic People''s Republic of Korea (North Korea) (2011–Present)',
  '10 of 11 Rome Statute Crimes Against Humanity Documented — UN Compared Abuses to Nazi Germany — Zero Accountability',
  'CRITICAL',
  'Kim Jong-un has governed North Korea as a totalitarian state since 2011, maintaining control through a system of political prison camps (kwanliso) housing an estimated 80,000–120,000 prisoners at any given time. The 2014 UN Commission of Inquiry on Human Rights in the DPRK — a 400-page report based on testimony from over 300 victims — concluded that North Korea has committed ''unspeakable atrocities'' constituting crimes against humanity, comparing them to crimes committed by Nazi Germany, and found ''policies established at the highest level of State'' directly responsible. An independent 2022 inquiry led by the International Bar Association''s War Crimes Committee found reasonable grounds to investigate Kim Jong-un personally for 10 of the 11 categories of crimes against humanity under the Rome Statute, including extermination, enslavement, torture, sexual violence, and enforced disappearances in detention centers. North Korea is not an ICC member state, and China''s UN Security Council veto blocks any international referral. As of April 2026, Kim Jong-un faces zero meaningful accountability.',
  '["February 17, 2014: UN Commission of Inquiry released landmark 400-page report concluding North Korea committed ''widespread, systematic and gross human rights violations'' amounting to crimes against humanity — based on testimony from 300+ victims and witnesses","COI Chair Justice Michael Kirby compared North Korean atrocities to those committed by Nazi Germany in World War II","COI documented crimes including extermination, murder, enslavement, torture, imprisonment, rape, forced abortions, sexual violence, persecution on political/religious/racial/gender grounds, forcible transfer, enforced disappearance, and deliberately inflicted starvation","2022 IBA War Crimes Committee and Committee for Human Rights in North Korea (HRNK) inquiry: found 10 of 11 Rome Statute crimes against humanity committed in detention centers; specifically identified Kim Jong-un, high-ranking officials, and guards as accountable","Estimated 80,000–120,000 political prisoners currently held in kwanliso; children as young as 7 forced into labor in detention camps","North Korea is not an ICC member state; China''s Security Council veto has blocked every international referral attempt","2014 COI letter to Kim Jong-un personally stated: ''The Commission has found that systematic, widespread and gross human rights violations have been, and are being, committed by the Democratic People''s Republic of Korea, its institutions and officials''","As of April 2026, no criminal proceedings of any kind have been initiated against Kim Jong-un or any senior DPRK official"]'::jsonb,
  '["UN COMMISSION FOUND CRIMES AGAINST HUMANITY 2014","IBA INQUIRY: 10/11 ROME STATUTE CRIMES 2022","NO ICC JURISDICTION","CHINA VETO BLOCKS REFERRAL","ZERO ACCOUNTABILITY"]'::jsonb,
  'UN Commission of Inquiry on Human Rights in the DPRK (February 2014): 400-page report based on 300+ testimonies concluding crimes against humanity ''of an unspeakable gravity'' are committed in North Korea, with ''policies established at the highest level of State.'' COI recommended ICC referral or special tribunal. IBA War Crimes Committee and HRNK 2022 inquiry: found 10 of 11 Rome Statute crimes against humanity in detention centers and identified Kim Jong-un and senior officials as accountable. HRW, Amnesty International, and UN Special Rapporteur annual reports consistently document ongoing systematic violations. North Korea is not an ICC member; China''s UNSC veto blocks referral. No prosecution in any forum as of April 2026.',
  '[{"url":"https://www.ohchr.org/en/press-releases/2014/02/north-korea-un-commission-documents-wide-ranging-and-ongoing-crimes-against","date":"2014-02-17","name":"UN OHCHR — North Korea: UN Commission Documents Crimes Against Humanity"},{"url":"https://www.ibanet.org/Inquiry-on-Crimes-Against-Humanity-in-North-Korean-Detention-Centers","date":"2022-07-01","name":"IBA — Inquiry on Crimes Against Humanity in North Korean Detention Centers (2022)"},{"url":"https://www.hrw.org/news/2017/03/06/north-korea-crimes-against-humanity-demand-justice","date":"2017-03-06","name":"HRW — North Korea: Crimes Against Humanity Demand Justice"},{"url":"https://www.hrw.org/world-report/2025/country-chapters/north-korea","date":"2024-12-11","name":"HRW — World Report 2025: North Korea"},{"url":"https://www.amnesty.org/en/location/asia-and-the-pacific/east-asia/north-korea/report-korea-democratic-peoples-republic-of/","date":"2024-01-01","name":"Amnesty International — Human Rights in North Korea (Annual Report)"}]'::jsonb,
  NULL,
  NULL
),
(
  'MIN AUNG HLAING',
  'Senior General, Commander-in-Chief of Myanmar Defence Services / President of Myanmar (April 2026–Present)',
  'ICC Arrest Warrant Application Filed — UN Found Genocidal Intent 2018 — ICJ Genocide Case Active 2026',
  'CRITICAL',
  'Min Aung Hlaing has commanded Myanmar''s military (Tatmadaw) since 2011 and leads the junta that seized power in a February 2021 coup. Under his direct command, Myanmar security forces launched a mass atrocity campaign against the Rohingya Muslim minority beginning August 25, 2017 — driving approximately 750,000 Rohingya from their homes in Rakhine State through mass killings, rape, and arson. The UN''s 2018 Independent Fact-Finding Mission found that Min Aung Hlaing and five other senior commanders oversaw these atrocities with ''genocidal intent'' and recommended their prosecution for genocide, crimes against humanity, and war crimes before the ICC. On November 27, 2024, the ICC Prosecutor formally requested an arrest warrant for Min Aung Hlaing for the crimes against humanity of deportation and persecution of the Rohingya. A parallel ICJ genocide case brought by The Gambia opened full hearings in January 2026. As of April 2026, the ICC Pre-Trial Chamber had not yet ruled on the warrant application; Min Aung Hlaing continues to govern Myanmar.',
  '["August 25 – December 31, 2017: Myanmar Tatmadaw campaign drove 700,000–750,000 Rohingya from Rakhine State through mass killings, rape, and burning of entire villages","August 27, 2018: UN Independent Fact-Finding Mission concluded Min Aung Hlaing and five commanders acted ''with genocidal intent'' and should be prosecuted for genocide, crimes against humanity, and war crimes before the ICC","UN Fact-Finding Mission report based on 847 interviews, satellite imagery, authenticated documents, photographs, and video covering abuses from 2011 onward","February 2021: Min Aung Hlaing led military coup overthrowing Aung San Suu Kyi''s elected government; post-coup crackdown used lethal force against protesters with thousands arrested, tortured, and killed in detention","November 14, 2019: ICC authorized investigation into Bangladesh/Myanmar situation covering Rohingya deportation","November 27, 2024: ICC Prosecutor filed arrest warrant application against Min Aung Hlaing for crimes against humanity of deportation and persecution of the Rohingya","January 2026: ICJ opened full genocide case against Myanmar (The Gambia v. Myanmar) — first full genocide hearing at the ICJ in over a decade","As of April 2026, ICC Pre-Trial Chamber had not yet ruled on the arrest warrant application; Min Aung Hlaing was appointed President of Myanmar in April 2026"]'::jsonb,
  '["ICC ARREST WARRANT APPLICATION PENDING (NOV 2024)","UN FOUND GENOCIDAL INTENT 2018","ICJ GENOCIDE CASE ACTIVE 2026","COUP LEADER","ROHINGYA MASS ATROCITY"]'::jsonb,
  'UN Independent Fact-Finding Mission on Myanmar (August 2018): concluded Min Aung Hlaing and five senior commanders oversaw atrocities in Rakhine, Kachin, and Shan states with ''genocidal intent''; recommended ICC prosecution. Report based on 847 interviews and extensive documentary and satellite evidence. ICC authorized Bangladesh/Myanmar investigation (November 14, 2019). ICC Prosecutor filed arrest warrant application against Min Aung Hlaing for crimes against humanity of deportation and persecution (November 27, 2024). ICJ Gambia v. Myanmar genocide case opened full hearing January 2026. Min Aung Hlaing led February 2021 coup and continued atrocities against civilian population; appointed Myanmar President April 2026.',
  '[{"url":"https://iimm.un.org/en/icc-situation-bangladeshmyanmar","date":"2024-11-27","name":"UN IIMM — ICC Situation Bangladesh/Myanmar: Prosecutor''s Arrest Warrant Application"},{"url":"https://www.hrw.org/news/2018/08/27/un-security-council-should-seek-justice-myanmar-atrocities","date":"2018-08-27","name":"HRW — UN Should Seek Justice for Myanmar Atrocities (UN Fact-Finding Mission Report)"},{"url":"https://www.aljazeera.com/news/2026/1/12/un-top-court-set-to-open-myanmar-rohingya-genocide-case","date":"2026-01-12","name":"Al Jazeera — UN Top Court Opens Myanmar Rohingya Genocide Case (ICJ January 2026)"},{"url":"https://www.icj.org/myanmar-icc-prosecutors-application-for-arrest-warrant-is-a-major-step-towards-justice-for-the-rohingya/","date":"2024-11-27","name":"ICJ — Myanmar: ICC Prosecutor''s Application for Arrest Warrant"},{"url":"https://www.amnesty.org/en/latest/news/2025/08/8-years-on-accountability-needed-for-myanmar-atrocities-against-rohingya/","date":"2025-08-07","name":"Amnesty International — 8 Years On: Accountability Needed for Myanmar Atrocities"}]'::jsonb,
  NULL,
  NULL
),
(
  'MARIA ALEKSEYEVNA LVOVA-BELOVA',
  'Commissioner for Children''s Rights, Office of the President of the Russian Federation',
  'ICC Arrest Warrant Active — War Crime of Unlawful Deportation of Ukrainian Children — Co-Accused with Vladimir Putin',
  'HIGH',
  'Maria Alekseyevna Lvova-Belova serves as Russia''s Presidential Commissioner for Children''s Rights. On March 17, 2023, the ICC issued simultaneous arrest warrants for both Lvova-Belova and Vladimir Putin for the war crime of unlawful deportation and transfer of Ukrainian children from occupied Ukrainian territory to the Russian Federation — the first ICC warrant ever issued against a sitting leader of a permanent UN Security Council member state. The ICC found reasonable grounds to believe she is individually criminally responsible as a direct perpetrator and as one who committed acts jointly with others. Ukrainian authorities have documented over 16,000 confirmed cases of children forcibly taken to Russia. Lvova-Belova publicly promoted the program on Russian state media, including describing personally ''adopting'' a Ukrainian child from Mariupol. All 124 ICC member states are legally obligated to arrest her upon entry to their territory. As of April 2026, the warrant remains active and unexecuted.',
  '["March 17, 2023: ICC issued arrest warrant for Lvova-Belova simultaneously with Putin''s warrant for the war crime of unlawful deportation and transfer of Ukrainian children (ICC-02/22-01/23)","Charges: ''Unlawful deportation of population (children) and unlawful transfer of population (children) from occupied areas of Ukraine to the Russian Federation'' under Articles 8(2)(a)(vii) and 8(2)(b)(viii) of the Rome Statute","ICC found she bears individual criminal responsibility ''for having committed the acts directly, jointly with others and/or through others''","Ukrainian authorities documented over 16,000 confirmed cases of children forcibly deported to Russia; total believed significantly higher","Lvova-Belova publicly promoted the deportation program on Russian state media, including describing personally adopting a Ukrainian child from Mariupol","First ICC arrest warrant ever issued against an official from a permanent UN Security Council member state","All 124 ICC member states are legally obligated to arrest her upon entry to their territory; Russia rejects ICC jurisdiction","As of April 2026, the warrant remains active and unexecuted"]'::jsonb,
  '["ICC ARREST WARRANT ACTIVE SINCE MARCH 2023","CO-ACCUSED WITH PUTIN","DIRECT PERPETRATOR FINDING","16,000+ DOCUMENTED CHILD DEPORTATIONS","NEVER ARRESTED"]'::jsonb,
  'ICC arrest warrant ICC-02/22-01/23 issued March 17, 2023 for unlawful deportation and transfer of Ukrainian children under Articles 8(2)(a)(vii) and 8(2)(b)(viii) of the Rome Statute. ICC Pre-Trial Chamber II found reasonable grounds to believe Lvova-Belova bears individual criminal responsibility as direct perpetrator, joint perpetrator, and perpetrator through others. Ukrainian authorities documented 16,000+ confirmed child deportation cases. Lvova-Belova publicly acknowledged and promoted the program on Russian state television, including describing adopting a Ukrainian child from Mariupol. All 124 ICC member states legally obligated to arrest her. Warrant is the first ever issued against an official of a permanent UN Security Council member state.',
  '[{"url":"https://www.icc-cpi.int/defendant/maria-alekseyevna-lvova-belova","date":"2023-03-17","name":"ICC Official — Maria Alekseyevna Lvova-Belova Defendant Page"},{"url":"https://www.europarl.europa.eu/thinktank/it/document/EPRS_BRI(2023)747093","date":"2025-02-10","name":"European Parliament — Russia''s War on Ukraine: Forcibly Displaced Ukrainian Children"},{"url":"https://en.wikipedia.org/wiki/International_Criminal_Court_arrest_warrants_for_Russian_leaders","date":"2023-03-17","name":"Wikipedia — ICC Arrest Warrants for Russian Leaders"},{"url":"https://www.cnn.com/2023/03/17/europe/icc-russia-war-crimes-charges-intl","date":"2023-03-17","name":"CNN — ICC Issues War Crimes Arrest Warrant for Putin and Lvova-Belova"},{"url":"https://media.un.org/unifeed/en/asset/d302/d3021548","date":"2023-03-17","name":"UN Media — ICC President Statement on Putin and Lvova-Belova Warrants"}]'::jsonb,
  NULL,
  NULL
),
(
  'DR. ANTHONY FAUCI',
  'Former Director, National Institute of Allergy and Infectious Diseases (NIAID) 1984–2022 / Former Chief Medical Adviser to the President',
  'Multiple DOJ Criminal Referrals for Perjury — Biden Autopen Pardon Constitutionality Disputed — NIH Wuhan Gain-of-Function Testimony Contradicted by Own Emails',
  'HIGH',
  'Dr. Anthony Fauci directed the NIAID for 38 years and served as the nation''s most prominent public health official throughout the COVID-19 pandemic. In May 2021 Senate testimony, he stated under oath that ''the NIH has not ever and does not now fund gain-of-function research in the Wuhan Institute of Virology.'' A 2023 House Select Subcommittee on the Coronavirus Pandemic report released emails — including a February 2020 email from Fauci acknowledging scientists at Wuhan University ''are known to have been working on gain-of-function experiments'' — that directly contradicted his sworn testimony. Senator Rand Paul submitted an official DOJ criminal referral in July 2023 for perjury under 18 U.S.C. § 1001. In January 2025, Biden issued Fauci a preemptive pardon — but a July 2025 New York Times report revealed the pardon was executed via autopen by White House staff, not personally authorized by Biden, raising its constitutional validity. Paul re-issued his criminal referral in July 2025, arguing the pardon is constitutionally void. As of April 2026, no criminal prosecution has occurred.',
  '["May 11, 2021: Fauci testified to the U.S. Senate under oath: ''The NIH has not ever and does not now fund gain-of-function research in the Wuhan Institute of Virology''","2023: House Select Subcommittee released FOIA emails including a February 2020 Fauci email acknowledging scientists at Wuhan were ''known to have been working on gain-of-function experiments'' — directly contradicting his sworn Senate testimony","2023 GAO report confirmed NIH funded research at the Wuhan Institute combining bat coronaviruses with SARS and MERS viruses, producing hybridized coronavirus strains","July 2023: Senator Rand Paul submitted official criminal referral to DOJ against Fauci for perjury under 18 U.S.C. § 1001 (knowingly making materially false statements to Congress)","January 2025: Biden granted Fauci a preemptive pardon shortly before leaving office","July 2025: New York Times reported Biden did not personally authorize all clemency decisions — Fauci''s pardon was executed via autopen by White House staff, raising constitutional validity questions","July 14, 2025: Senator Rand Paul renewed criminal referral to Trump DOJ, citing both original perjury allegations and questionable constitutional validity of the autopen pardon","As of April 2026, no criminal prosecution of Fauci has been initiated; he denies all wrongdoing"]'::jsonb,
  '["DOJ CRIMINAL REFERRAL 2023","RENEWED DOJ CRIMINAL REFERRAL 2025","AUTOPEN PARDON CONSTITUTIONALITY DISPUTED","PERJURY ALLEGATION — CONTRADICTED BY OWN EMAILS","NO PROSECUTION"]'::jsonb,
  'May 2021 Senate testimony: Fauci stated under oath the NIH did not fund gain-of-function research at the Wuhan Institute of Virology. 2023 House Select Subcommittee FOIA document release: February 2020 Fauci email acknowledging Wuhan scientists ''are known to have been working on gain-of-function experiments,'' contradicting sworn testimony. 2023 GAO report: NIH funded research at WIV involving bat coronaviruses combined with SARS/MERS producing hybridized strains. July 2023 criminal referral by Sen. Rand Paul to DOJ for perjury under 18 U.S.C. § 1001. January 2025 preemptive Biden pardon. July 2025 New York Times report: Biden autopen pardon not personally authorized by president. July 14, 2025 renewed criminal referral citing both original perjury and pardon constitutional invalidity.',
  '[{"url":"https://www.hsgac.senate.gov/media/reps/senator-rand-paul-re-refers-dr-anthony-fauci-to-the-department-of-justice/","date":"2025-07-14","name":"U.S. Senate HSGAC — Senator Rand Paul Re-Refers Fauci to DOJ (July 14, 2025)"},{"url":"https://dallasexpress.com/national/u-s-sen-paul-presses-doj-probe-faucis-truthfulness-bidens-autopen-pardon/","date":"2025-07-14","name":"Dallas Express — Paul Presses DOJ on Fauci Truthfulness and Biden Autopen Pardon"},{"url":"https://childrenshealthdefense.org/defender/rand-paul-anthony-fauci-doj-investigation-covid/","date":"2023-08-09","name":"Children''s Health Defense — Rand Paul Accuses Fauci of Perjury, Calls for DOJ Investigation"},{"url":"https://www.cpac.org/post/rand-paul-renews-criminal-probe-of-fauci-after-legitimacy-of-biden-s-autopen-pardon-is-questioned","date":"2025-07-15","name":"CPAC — Rand Paul Renews Criminal Probe of Fauci After Autopen Pardon Questions"}]'::jsonb,
  NULL,
  NULL
),
(
  'KLAUS SCHWAB',
  'Founder & Former Executive Chairman, World Economic Forum (WEF) / Creator of ''The Great Reset'' and ''Fourth Industrial Revolution'' Frameworks',
  'Resigned April 2025 Under Whistleblower Investigation — WEF Internal Probe Finds Unauthorized Spending, Bullying, Inappropriate Conduct',
  'HIGH',
  'Klaus Schwab founded the World Economic Forum in 1971 and built it into the world''s most influential private convening body for global elites, governments, and corporations. He resigned unexpectedly as WEF Chairman on April 18, 2025 — without explanation — one day before the board announced it had launched an independent investigation in response to an anonymous whistleblower letter from current and former WEF employees. The letter alleged Schwab and his wife, Hilde, misused WEF organizational resources for personal benefit without appropriate oversight, including unauthorized spending and luxury travel. By July 2025, the WEF''s investigation concluded, finding evidence of unauthorized expenditures, workplace bullying, and inappropriate conduct toward female employees including a 2020 late-night personal email to a senior female executive. Schwab denied all allegations and filed defamation complaints against the anonymous whistleblowers. Beyond the internal investigation, Schwab''s WEF is the primary global institution promoting the ''Great Reset'' framework — calling for state-corporate fusion, ESG mandates, and centralized digital governance — making him a central figure in accountability research regarding elite capture of international institutions.',
  '["April 18, 2025: Schwab resigned as WEF Chairman effective immediately without public explanation — one day before the board announced an investigation","April 2025: WEF board launched independent investigation following anonymous whistleblower letter from current and former employees alleging financial misconduct and ethical violations by Schwab and his wife Hilde","Wall Street Journal first reported (April 22, 2025): allegations included Schwab family intertwining personal matters with WEF resources, having subordinates make ATM cash withdrawals on his behalf, and luxury hotel massage charges billed to the WEF","July 23, 2025: WSJ reported the WEF internal investigation found evidence of unauthorized expenditures by Schwab and wife, bullying of staff, and a late-night June 2020 email to a senior female executive asking ''Do you feel that I am thinking of you?''","Schwab via spokesperson broadly denied all conclusions and defended his 55-year tenure at the WEF","Schwab filed defamation complaints against the anonymous whistleblowers","No criminal charges filed as of April 2026; matter remains a civil and governance investigation","Schwab''s WEF is the primary institution promoting the ''Great Reset,'' ''Fourth Industrial Revolution,'' and ''stakeholder capitalism'' — frameworks critics document as templates for global elite governance override of democratic accountability"]'::jsonb,
  '["RESIGNED UNDER INVESTIGATION APRIL 2025","WEF PROBE FINDINGS: UNAUTHORIZED SPENDING + WORKPLACE MISCONDUCT","WHISTLEBLOWER COMPLAINT","GREAT RESET ARCHITECT","NO CRIMINAL CHARGES"]'::jsonb,
  'April 18, 2025: Schwab resigned as WEF Chairman without explanation. Anonymous whistleblower letter to WEF board (April 2025) from current and former employees alleging: Schwab family use of WEF resources for personal benefit; subordinates directed to make ATM cash withdrawals on Schwab''s behalf; luxury hotel in-room massage charges billed to the WEF; wife Hilde Schwab arranging token meetings to justify luxury travel on WEF funds. WEF independent investigation launched April 22, 2025. July 23, 2025: Investigation concluded finding unauthorized expenditures by Schwab and wife, workplace bullying, and inappropriate late-night personal email to female executive (June 2020). Schwab denied all findings; filed defamation complaints. No criminal proceedings initiated as of April 2026.',
  '[{"url":"https://www.reuters.com/world/world-economic-forum-launches-probe-into-founder-klaus-schwab-over-whistleblower-2025-04-22/","date":"2025-04-22","name":"Reuters — WEF Launches Probe into Founder Klaus Schwab Over Whistleblower Letter"},{"url":"https://www.wsj.com/business/world-economic-forum-opens-new-probe-into-founder-klaus-schwab-e2f061d6","date":"2025-04-22","name":"Wall Street Journal — WEF Opens New Probe Into Founder Klaus Schwab"},{"url":"https://www.wsj.com/business/world-economic-forum-probe-of-klaus-schwab-finds-unauthorized-spending-and-inappropriate-behavior-b1dd6028","date":"2025-07-23","name":"Wall Street Journal — WEF Probe Finds Unauthorized Spending and Inappropriate Behavior"},{"url":"https://www.nytimes.com/2025/05/14/business/world-economic-forum-davos-klaus-schwab.html","date":"2025-05-14","name":"New York Times — World Economic Forum Investigating Allegations Against Its Founder"},{"url":"https://en.wikipedia.org/wiki/Klaus_Schwab","date":"2025-07-24","name":"Wikipedia — Klaus Schwab: Resignation and Investigation"}]'::jsonb,
  NULL,
  NULL
)
ON CONFLICT DO NOTHING;