/*
  # Enemies of Truth — Batch 3: SBF, Sacklers, Murdoch, Shkreli, Ghosn

  1. New Entries in `enemies_of_truth`
    - Sam Bankman-Fried (CRITICAL): FTX cryptocurrency fraud — convicted, 25 years, $11B forfeiture
    - The Sackler Family / Purdue Pharma (CRITICAL): OxyContin opioid epidemic — 3 federal felonies, $5.5B penalties
    - Rupert Murdoch (CRITICAL): News International phone hacking — Leveson Inquiry: "not a fit person"
    - Martin Shkreli (HIGH): Securities fraud — convicted 2017, 7 years, lifetime pharma ban
    - Carlos Ghosn (HIGH): Financial disclosure fraud — charged, fled Japan, fugitive in Lebanon

  2. Security
    - No schema changes; inserting into existing RLS-enabled table
*/

INSERT INTO enemies_of_truth (name, title, subtitle, severity, summary, key_facts, status_tags, evidence_documented, sources) VALUES
(
  'SAM BANKMAN-FRIED',
  'Former CEO of FTX',
  'FTX Cryptocurrency Fraud — Convicted, 25 Years Federal Prison, $11B Forfeiture',
  'CRITICAL',
  'Sam Bankman-Fried founded FTX in 2019 and built it into the world''s second-largest cryptocurrency exchange, valued at $32 billion, before its collapse in November 2022. Throughout FTX''s operation, Bankman-Fried secretly transferred customer deposits to his affiliated trading firm Alameda Research, which used the funds to cover trading losses, purchase $1.8 billion in real estate, fund hundreds of millions in political donations and lobbying expenditures, and enrich Bankman-Fried personally. At the time FTX filed for Chapter 11 bankruptcy on November 11, 2022, an estimated $8 billion in customer funds was missing. The Department of Justice described it as "one of the largest financial frauds in history." Bankman-Fried was convicted on all seven counts on November 2, 2023, and sentenced to 25 years in federal prison on March 28, 2024, with $11 billion in forfeiture ordered.',
  '["FTX customer deposits secretly transferred to Alameda Research to cover trading losses, fund $1.8B in real estate, and make personal investments", "FTX filed Chapter 11 bankruptcy Nov 11, 2022; valued at $32 billion; approximately $8 billion in customer funds unaccounted for", "Arrested in the Bahamas Dec 12, 2022; extradited to the United States", "Three top lieutenants — Caroline Ellison, Gary Wang, Nishad Singh — pleaded guilty and cooperated as prosecution witnesses", "Conviction Nov 2, 2023: Guilty all 7 counts (2 wire fraud, 2 wire fraud conspiracy, securities fraud conspiracy, commodities fraud conspiracy, money laundering conspiracy)", "Sentence March 28, 2024: 25 years; $11 billion forfeiture; Judge Kaplan: ''this man will be in a position to do something very bad in the future, and it''s not a trivial risk''"]'::jsonb,
  '["CONVICTED — ALL 7 COUNTS", "25 YEARS FEDERAL PRISON", "$11B FORFEITURE"]'::jsonb,
  'FTX customers deposited funds believing they were held by the exchange; those funds were secretly transferred to Alameda Research and used to cover trading losses, fund real estate purchases, and make personal investments. FTX filed for Chapter 11 bankruptcy November 11, 2022; approximately $8 billion in customer funds unaccounted for. Three of Bankman-Fried''s top lieutenants — Caroline Ellison (Alameda CEO), Gary Wang (FTX CTO), and Nishad Singh (engineering head) — pleaded guilty and cooperated as prosecution witnesses. Conviction November 2, 2023: Guilty on all 7 counts. Sentence March 28, 2024: 25 years federal prison; $11 billion forfeiture.',
  '[{"url": "https://www.justice.gov/archives/opa/pr/samuel-bankman-fried-sentenced-25-years-his-orchestration-multiple-fraudulent-schemes", "date": "2024-03-28", "name": "DOJ — Bankman-Fried Sentenced to 25 Years"}, {"url": "https://www.justice.gov/usao-sdny/pr/samuel-bankman-fried-sentenced-25-years-prison", "date": "2024-03-28", "name": "DOJ SDNY — Bankman-Fried Sentenced"}]'::jsonb
),
(
  'THE SACKLER FAMILY / PURDUE PHARMA',
  'Purdue Pharma Owners',
  'OxyContin Opioid Epidemic — 3 Federal Felonies, $5.5B Criminal Penalties',
  'CRITICAL',
  'Purdue Pharma, controlled entirely by the Sackler family, aggressively marketed OxyContin beginning in 1996 while knowing the drug caused severe addiction, falsely representing to physicians and regulators that its time-release formulation carried a low addiction risk. The company paid kickbacks to high-prescribing physicians through sham speaker programs, lied to the DEA about its anti-diversion program''s effectiveness, and continued marketing to known high-risk prescribers even after its own internal data identified signs of abuse and diversion — including repeatedly visiting one doctor known to patients as "the Candyman" over 300 times. Purdue Pharma pleaded guilty to three federal felony charges on November 24, 2020, agreeing to criminal penalties totaling $5.544 billion — the largest ever levied against a pharmaceutical manufacturer. The opioid epidemic linked to Purdue''s marketing has contributed to more than 500,000 opioid-related deaths in the United States since 2000. No individual member of the Sackler family has been criminally charged; the family agreed in principle to a $7.4 billion civil settlement in 2025.',
  '["Purdue Frederick Co. (predecessor) pleaded guilty to felony misbranding of OxyContin in 2007, paying ~$600M — then continued the same marketing practices", "Despite 2007 conviction, Purdue continued marketing OxyContin to known high-risk prescribers through 2017, falsely representing effective anti-diversion program to DEA", "DOJ documented Purdue sent sales reps to visit a physician known as ''the Candyman'' (''crazy dosing of OxyContin'') more than 300 times", "Nov 24, 2020 guilty plea to 3 federal felonies: (1) conspiracy to defraud U.S./violate FDCA; (2) conspiracy to violate Anti-Kickback Statute via doctor payments; (3) conspiracy to violate AKS via Practice Fusion EHR kickbacks", "Criminal penalties: $3.544B fine + $2B forfeiture = $5.544B — largest ever against a pharmaceutical manufacturer", "DOJ: ''resolutions do not include criminal release of any individuals, including members of the Sackler family''; Sackler family agreed to $7.4B civil settlement (2025); barred from selling opioids in U.S."]'::jsonb,
  '["3 FEDERAL FELONY CONVICTIONS", "$5.544B CRIMINAL PENALTIES", "500,000+ OPIOID DEATHS / NO SACKLER CHARGED"]'::jsonb,
  'Purdue Frederick Co. predecessor guilty plea to felony misbranding in 2007, paying approximately $600 million. Continued marketing OxyContin to known high-risk prescribers through 2017 despite 2007 conviction. DOJ documentation of sales representatives visiting a physician known as "the Candyman" more than 300 times. November 24, 2020 guilty plea to 3 federal felony counts: conspiracy to defraud U.S./violate FDCA, conspiracy to violate Anti-Kickback Statute through doctor speaker payments, conspiracy to violate AKS through Practice Fusion EHR kickbacks. Criminal penalties totaling $5.544 billion — largest ever against a pharmaceutical manufacturer. DOJ explicitly stated resolutions do not include criminal release of any individuals including Sackler family members.',
  '[{"url": "https://www.justice.gov/archives/opa/pr/opioid-manufacturer-purdue-pharma-pleads-guilty-fraud-and-kickback-conspiracies", "date": "2020-11-24", "name": "DOJ — Purdue Pharma Pleads Guilty"}, {"url": "https://www.justice.gov/archives/opa/pr/justice-department-announces-global-resolution-criminal-and-civil-investigations-opioid", "date": "2020-10-21", "name": "DOJ — Global Resolution with Purdue Pharma"}, {"url": "https://oig.hhs.gov/fraud/enforcement/justice-department-announces-global-resolution-of-criminal-and-civil-investigations-with-opioid-manufacturer-purdue-pharma-and-civil-settlement-with-members-of-the-sackler-family/", "date": "2020-10-21", "name": "HHS OIG — Purdue Pharma Resolution"}, {"url": "https://portal.ct.gov/ag/press-releases/2025-press-releases/purdue-pharma-and-sackler-family-settlement-in-principle", "date": "2025", "name": "Connecticut AG — Sackler Family Settlement in Principle"}]'::jsonb
),
(
  'RUPERT MURDOCH',
  'Chairman Emeritus of News Corp / Fox Corporation',
  'News International Phone Hacking & Cover-Up — Leveson Inquiry: "Not a Fit Person"',
  'CRITICAL',
  'Rupert Murdoch''s British newspaper subsidiary News International — publishing the News of the World and The Sun — engaged in systematic phone hacking, police bribery, and deliberate destruction of evidence across more than a decade, targeting more than 4,000 potential victims including celebrities, politicians, members of the royal family, crime victims, relatives of deceased soldiers, and 13-year-old murder victim Milly Dowler (whose voicemails were hacked while she was still missing, briefly giving her family false hope). The Leveson Inquiry (2011–2012), commissioned by Prime Minister David Cameron, found that Murdoch "exhibited wilful blindness to what was going on in his companies." The House of Commons Culture, Media and Sport Select Committee concluded on May 1, 2012 that he was "not a fit person to exercise the stewardship of a major international company." Over 30 million emails were deleted in what investigators described as deliberate evidence destruction. In 2023, News Group Newspapers admitted to operating a "criminal enterprise" during settlement proceedings with Prince Harry.',
  '["News of the World journalists and PI Glenn Mulcaire hacked voicemails of 4,000+ targets including murder victim Milly Dowler, 7/7 bombing victims, deceased soldiers'' relatives", "Systematic police bribery (Operation Elveden): journalists made payments to serving Metropolitan Police officers for confidential information", "Senior executives including CEO Rebekah Brooks maintained 2007 ''rogue reporter'' cover story; Murdoch admitted ''a cover-up'' had taken place; 30 million+ emails deleted", "Leveson Inquiry (Nov 2012, 2,000 pages): Murdoch ''exhibited wilful blindness to what was going on in his companies''", "House of Commons Select Committee (May 1, 2012): Murdoch ''not a fit person to exercise the stewardship of a major international company''", "News Group Newspapers admitted in 2023 settlement with Prince Harry it had operated a ''criminal enterprise''; Andy Coulson convicted of conspiracy to hack phones — 18 months"]'::jsonb,
  '["NOT A FIT PERSON — COMMONS FINDING", "4,000+ HACKING VICTIMS", "30M+ EMAILS DELETED"]'::jsonb,
  'News of the World journalists and private investigator Glenn Mulcaire hacked voicemails of over 4,000 potential targets. Systematic police bribery documented as institutional practice. Senior executives maintained cover story; Murdoch admitted to Leveson Inquiry that "a cover-up" had taken place; over 30 million emails deleted. Leveson Inquiry Report (November 2012): Murdoch "exhibited wilful blindness to what was going on in his companies." House of Commons Culture, Media and Sport Select Committee (May 1, 2012): Murdoch was "not a fit person to exercise the stewardship of a major international company." News Group Newspapers admitted in 2023 settlement proceedings with Prince Harry it had operated a "criminal enterprise." Andy Coulson convicted of conspiracy to hack phones, sentenced to 18 months.',
  '[{"url": "https://www.gov.uk/government/publications/leveson-inquiry-report-into-the-culture-practices-and-ethics-of-the-press", "date": "2012-11", "name": "Leveson Inquiry Report — UK National Archives"}, {"url": "https://publications.parliament.uk/pa/cm201012/cmselect/cmcul/903/903.pdf", "date": "2012-05-01", "name": "House of Commons — News International and Phone-Hacking Report"}, {"url": "https://www.hackedoff.org/blog-posts/https-hackinginquiry-org-murdoch-admits-to-cover-up-of-phone-hacking-at-news-of-the-world", "date": "2012-04-26", "name": "Hacked Off — Murdoch Admits Cover-Up"}, {"url": "https://www.nbcnews.com/news/world/leveson-report-rupert-murdoch-son-evidence-suggests-cover-somebody-flna1c7339773", "date": "2012-11-29", "name": "NBC News — Leveson Report on Murdoch"}, {"url": "https://www.bbc.com/news/uk-england-london-68615789", "date": "2024-03", "name": "BBC — Murdoch Must Have Known of Phone Hacking"}]'::jsonb
),
(
  'MARTIN SHKRELI',
  'Former CEO of Turing Pharmaceuticals / Retrophin',
  'Securities Fraud — Convicted 2017, 7 Years Federal Prison, $64.6M Disgorgement, Lifetime Pharma Ban',
  'HIGH',
  'Martin Shkreli became publicly known in 2015 when his pharmaceutical company Turing Pharmaceuticals raised the price of antiparasitic drug Daraprim by 5,500% overnight. He was convicted on federal securities fraud charges in August 2017 for separate schemes: defrauding investors in two hedge funds (MSMB Capital and MSMB Healthcare) through fabricated account statements and misappropriated assets, and manipulating the stock of publicly traded Retrophin by secretly controlling a large share position and then using unauthorized company funds to pay off defrauded hedge fund investors through fabricated consulting agreements. A 2022 federal civil ruling separately found his Daraprim price-gouging constituted an illegal anticompetitive conspiracy, ordering $64.6 million in disgorgement and a permanent ban from the pharmaceutical industry. He served approximately five years before release in May 2022.',
  '["MSMB Capital fraud: false representations to induce $3M+ in investments; misappropriated assets; fabricated account statements with fictitious balances; raided Retrophin to cover losses", "Retrophin manipulation: secretly controlled large share position; used unauthorized company funds (no board approval) to pay off defrauded MSMB investors through fabricated consulting agreements", "Conviction Aug 4, 2017 (E.D.N.Y.): guilty on 2 counts securities fraud (MSMB Capital, MSMB Healthcare) and 1 count conspiracy (Retrophin); Case: U.S. v. Shkreli, No. 15-CR-637", "Sentence March 9, 2018: 7 years federal prison; $75,000 fine; $7.3M forfeiture including Wu-Tang Clan''s ''Once Upon a Time in Shaolin'' album", "2022 civil ruling: $64.6M disgorgement of Daraprim profits; found to constitute illegal anticompetitive conspiracy; permanently banned from pharmaceutical industry", "Second Circuit affirmed conviction July 2019; Supreme Court denied review"]'::jsonb,
  '["CONVICTED — SECURITIES FRAUD", "LIFETIME PHARMA BAN", "$64.6M DISGORGEMENT"]'::jsonb,
  'MSMB Capital fraud: Shkreli used false representations to induce investors to place over $3 million in his hedge fund; misappropriated assets; fabricated account statements; raided Retrophin to cover losses. Retrophin stock manipulation: secretly controlled large share position; used unauthorized company funds without board approval to pay off defrauded investors through fabricated consulting agreements. Conviction August 4, 2017 (E.D.N.Y.): guilty on 2 counts securities fraud and 1 count conspiracy. Sentence March 9, 2018: 7 years federal prison; $7.3 million forfeiture. 2022 civil ruling: $64.6 million disgorgement; permanent pharmaceutical industry ban. Second Circuit affirmed conviction July 2019; Supreme Court denied review.',
  '[{"url": "https://www.justice.gov/usao-edny/pr/martin-shkreli-sentenced-seven-years-imprisonment-multi-million-dollar-fraud-scheme", "date": "2018-03-09", "name": "DOJ — Shkreli Sentenced to Seven Years"}, {"url": "https://www.justice.gov/usao-edny/pr/former-hedge-fund-manager-convicted-multi-million-dollar-fraud-scheme", "date": "2017-08-04", "name": "DOJ — Shkreli Convicted"}, {"url": "https://www.justice.gov/usao-edny/pr/united-states-sells-unique-wu-tang-clan-album-forfeited-convicted-hedge-fund-manager", "date": "2021", "name": "DOJ — Wu-Tang Album Forfeiture Sale"}]'::jsonb
),
(
  'CARLOS GHOSN',
  'Former CEO of Nissan-Renault Alliance',
  'Financial Disclosure Fraud — Charged, Fled Japan, Fugitive in Lebanon',
  'HIGH',
  'Carlos Ghosn was arrested at Tokyo Narita Airport on November 19, 2018 on four counts of financial misconduct: underreporting approximately 9.3 billion yen ($80 million) in deferred compensation in Nissan''s official securities filings to Japan''s Financial Services Agency over eight fiscal years; temporarily shifting personal investment losses onto Nissan''s balance sheet; and directing $49.7 million in payments through Nissan''s Middle Eastern distributor networks to associates who allegedly funneled funds back to Ghosn personally. While awaiting trial under 24-hour surveillance, Ghosn was smuggled out of Japan on December 29–30, 2019 — hidden in a large audio equipment case — and flown by private jet through Istanbul to Beirut, Lebanon, which has no extradition treaty with Japan. He remains in Lebanon, subject to an Interpol Red Notice, and has not faced trial on the substantive charges. In a parallel U.S. proceeding, Ghosn paid a $1 million SEC fine and accepted a 10-year bar from serving as an officer of any U.S. reporting company.',
  '["Counts 1–2: Underreporting ~9.3 billion yen ($80M) in deferred compensation in Nissan securities filings to Japan FSA across fiscal years 2010–2018", "Count 3 (Saudi Arabia): Temporarily transferred 1.85 billion yen in personal losses to Nissan balance sheet; directed $14.7M in Nissan payments to Saudi associate as reimbursement", "Count 4 (Oman): Directed Nissan Middle East to make $35M payments to Omani dealer (2011–2018) with funds alleged to flow back to Ghosn and family", "Escape: smuggled out of Japan Dec 29–30, 2019 hidden in audio equipment case; flown via Istanbul to Beirut; Michael and Peter Taylor convicted (2 years, 1 year 8 months)", "Nissan pleaded guilty and fined 200 million yen; executive Greg Kelly convicted March 2022 for concealing compensation for one fiscal year", "SEC: Ghosn paid $1M fine and accepted 10-year bar from officer/director positions at U.S. reporting companies"]'::jsonb,
  '["INTERPOL RED NOTICE — FUGITIVE", "FLED JAPAN IN EQUIPMENT CASE", "SEC $1M FINE / 10-YEAR BAR"]'::jsonb,
  'Four counts of financial misconduct: underreporting approximately 9.3 billion yen in deferred compensation across fiscal years 2010–2018; temporarily shifting personal investment losses onto Nissan balance sheet; directing $49.7 million through Nissan Middle Eastern distributor networks. Escape from Japan December 29–30, 2019 hidden in audio equipment case; flown via Istanbul to Beirut. Michael and Peter Taylor convicted by Tokyo court July 2021 (2 years and 1 year 8 months respectively). Nissan Motor Co. pleaded guilty and fined 200 million yen; Greg Kelly convicted March 2022. SEC administrative proceedings: $1 million fine and 10-year officer/director bar.',
  '[{"url": "https://www.bbc.com/news/business-60597994", "date": "2022-03-02", "name": "BBC — Former Nissan Executive Convicted Over Ghosn Pay Case"}, {"url": "https://www.reuters.com/business/american-duo-sentenced-prison-by-tokyo-court-helping-ghosn-flee-japan-2021-07-19/", "date": "2021-07-19", "name": "Reuters — American Duo Sentenced for Helping Ghosn Flee"}, {"url": "https://www.pbs.org/newshour/economy/whats-known-about-ghosns-case-after-his-escape", "date": "2020-01", "name": "PBS — What''s Known About Ghosn''s Case After Escape"}, {"url": "https://www.sec.gov/files/litigation/apdocuments/3-18127-event-22.pdf", "date": "2019", "name": "SEC — Administrative Proceedings Against Ghosn"}]'::jsonb
);