/*
  # Enemies of Truth — Batch 2: Kissinger, Putin, Chirac, Holmes, Madoff, Enron

  1. New Entries in `enemies_of_truth`
    - Henry Kissinger (CRITICAL): Cambodia secret bombing, Chile coup (Operation FUBELT), Operation Condor
    - Vladimir Putin (CRITICAL): Panama Papers $2B shell network, OPCW-confirmed Novichok poisoning of Navalny
    - Jacques Chirac (HIGH): Criminal conviction for embezzlement — first French president convicted since WWII
    - Elizabeth Holmes (CRITICAL): Theranos blood-testing fraud — convicted, 11 years federal prison
    - Bernie Madoff (CRITICAL): Largest Ponzi scheme in financial history — convicted, 150 years, $170B forfeiture
    - Kenneth Lay & Jeffrey Skilling / Enron (CRITICAL): Enron accounting fraud — convicted 2006, largest corporate bankruptcy of its era

  2. Security
    - No schema changes; inserting into existing RLS-enabled table
*/

INSERT INTO enemies_of_truth (name, title, subtitle, severity, summary, key_facts, status_tags, evidence_documented, sources) VALUES
(
  'HENRY KISSINGER',
  'Former Secretary of State & National Security Advisor (1969–1977)',
  'Cambodia Secret Bombing, Chile Coup (Operation FUBELT) & Operation Condor',
  'CRITICAL',
  'Declassified documents — including CIA cables, NSC memoranda, and more than 30,000 pages of Kissinger''s own secretly recorded telephone transcripts (telcons) obtained through FOIA litigation — establish his direct role in three major covert operations. From March 1969 to May 1970, Kissinger managed the cover-up of the secret U.S. bombing of Cambodia (Operation Menu), during which military reports were falsified to show strikes occurred in South Vietnam and congressional committees were deliberately misled. CIA cables from October 16, 1970 record his deputy conveying to the CIA station in Santiago: "It is firm and continuing policy that Allende be overthrown by a coup" — placing Kissinger as the named supervisor of covert operations (Project FUBELT) against Chile''s democratically elected government. Kissinger was also briefed in June 1976 on Operation Condor''s cross-border assassination program and took no action to stop U.S. collaboration, weeks before the September 21, 1976 car-bomb assassination of former Chilean ambassador Orlando Letelier in Washington, D.C.',
  '["CIA Director Helms''s Sept 15, 1970 handwritten notes: Nixon''s order to ''make the economy scream'' in Chile, with Kissinger named personal supervisor — designated Project FUBELT", "CIA cables Oct 16, 1970: Kissinger''s deputy to CIA Santiago station chief: ''It is firm and continuing policy that Allende be overthrown by a coup''", "Operation Menu (Cambodia, March 1969 – May 1970): military reports falsified to show strikes in South Vietnam; Kissinger demanded Laird defend original decision", "CIA cables document U.S. involvement in assassination of Chilean Army Commander-in-Chief General Rene Schneider (Oct 22, 1970) — Kissinger-approved coup plotting", "State Dept demarche to halt Operation Condor assassinations authorized mid-1976; Kissinger ordered ''no further action'' — effectively canceling it before Letelier assassination (Sept 21, 1976)", "Meeting Pinochet, June 1976: ''You did a great service to the West in overthrowing Allende''"]'::jsonb,
  '["NAMED COUP SUPERVISOR — PROJECT FUBELT", "CAMBODIA BOMBING COVER-UP", "OPERATION CONDOR COMPLICITY"]'::jsonb,
  'CIA Director Richard Helms''s September 15, 1970 handwritten notes recording Nixon''s order to "make the economy scream" in Chile with Kissinger named personal supervisor of covert operations designated Project FUBELT. CIA cables dated October 16, 1970 recording Kissinger''s deputy conveying his direct order to the CIA Station Chief in Santiago: "It is firm and continuing policy that Allende be overthrown by a coup." Operation Menu documentation (Cambodia secret bombing, March 18, 1969 – May 26, 1970): military reports falsified to show strikes in South Vietnam; Kissinger''s telcon recordings show him demanding Defense Secretary Laird defend the original decision. CIA cables documenting U.S. involvement in the assassination of Chilean Army Commander-in-Chief General Rene Schneider (October 22, 1970). State Department demarche drafted to halt Operation Condor''s international assassinations, subsequently canceled by Kissinger''s "no further action" order — before the Letelier-Moffitt assassination on September 21, 1976.',
  '[{"url": "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB8/nsaebb8i.htm", "date": "1970", "name": "National Security Archive — Chile Declassified (Project FUBELT)"}, {"url": "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB437/", "date": "2013", "name": "National Security Archive — Kissinger and Chile"}, {"url": "https://nsarchive.gwu.edu/briefing-book/chile-cold-war-henry-kissinger-indonesia-southern-cone-vietnam/2023-11-29/henry", "date": "2023-11-29", "name": "National Security Archive — Kissinger Declassified Obituary"}, {"url": "https://www.cia.gov/readingroom/document/loc-hak-459-5-5-2", "date": "1969", "name": "CIA FOIA Reading Room — Cambodia Actions Documents"}, {"url": "https://www.intelligence.senate.gov/resources/intelligence-related-commissions", "date": "1975", "name": "Church Committee — Covert Action in Chile 1963–1973"}, {"url": "https://nsarchive.gwu.edu/events/operation-condor-1975-1980", "date": "1975", "name": "National Security Archive — Operation Condor Documents"}]'::jsonb
),
(
  'VLADIMIR PUTIN',
  'President of the Russian Federation',
  'Panama Papers $2B Shell Network & OPCW-Confirmed Novichok Poisoning of Navalny',
  'CRITICAL',
  'Vladimir Putin is implicated in documented corruption through the Panama Papers — an 11.5 million-document leak establishing a $2 billion network of shell companies transacted through his close associates — and in the chemical weapons poisoning of opposition leader Alexei Navalny, confirmed by the Organisation for the Prohibition of Chemical Weapons (OPCW) and independent military laboratories in Germany, France, and Sweden. The ICIJ''s April 2016 Panama Papers investigation documented a network of secret offshore transactions linked to Putin''s associates, including childhood friend Sergei Roldugin, with assets held through proxies in a pattern consistent with state-controlled kleptocracy. Navalny collapsed on a domestic Russian flight on August 20, 2020; the OPCW''s October 2020 report confirmed he was exposed to a Novichok nerve agent — a chemical weapon banned under the Chemical Weapons Convention. Navalny returned to Russia in January 2021, was imprisoned, and died in a Russian Arctic penal colony on February 16, 2024, under disputed circumstances.',
  '["ICIJ Panama Papers (April 2016): ''a network of secret offshore deals and vast loans worth $2 billion'' linked to Putin associates, including transactions through Sergei Roldugin via Mossack Fonseca shells", "OPCW Report S-1906-2020 (Oct 6, 2020): Navalny samples contained biomarkers of Novichok nerve agent matching CWC schedules 1.A.14 and 1.A.15", "OPCW findings independently confirmed by military laboratories in Germany (Bundeswehr), France, and Sweden", "OPCW Director-General Arias: results ''constitute a matter of grave concern''; Russia denied involvement and refused criminal investigation", "Separate OPCW report (April 2018) confirmed Novichok use in Salisbury, UK poisoning of Sergei Skripal; third victim Dawn Sturgess died", "Navalny arrested upon return to Russia Jan 2021; died in FKU IK-6 Polar Wolf penal colony Feb 16, 2024"]'::jsonb,
  '["$2B OFFSHORE SHELL NETWORK", "OPCW-CONFIRMED NOVICHOK POISONING", "NAVALNY DIED IN CUSTODY 2024"]'::jsonb,
  'International Consortium of Investigative Journalists (April 2016) documenting "a network of secret offshore deals and vast loans worth $2 billion" linked to Putin''s close associates through Mossack Fonseca shell companies. OPCW Report S-1906-2020 (October 6, 2020) confirming biomedical samples from Alexei Navalny contained biomarkers of a Novichok nerve agent with "similar structural characteristics as the toxic chemicals belonging to schedules 1.A.14 and 1.A.15" of the Chemical Weapons Convention. Independent confirmation by military laboratories in Germany (Bundeswehr), France, and Sweden. Separate OPCW report (April 2018) confirming Novichok use in the Salisbury, UK poisoning of Sergei Skripal attributed to Russian GRU operatives. Documentation of Navalny''s arrest upon return to Russia in January 2021 and death in FKU IK-6 Polar Wolf penal colony on February 16, 2024.',
  '[{"url": "https://www.opcw.org/sites/default/files/documents/2020/10/s-1906-2020(e).pdf", "date": "2020-10-06", "name": "OPCW Report S-1906-2020 — Navalny Poisoning"}, {"url": "https://www.opcw.org/media-centre/news/2020/10/opcw-issues-report-technical-assistance-requested-germany", "date": "2020-10", "name": "OPCW Media Release — Technical Assistance Report"}, {"url": "https://www.icij.org/investigations/panama-papers/20160403-panama-papers-global-overview/", "date": "2016-04", "name": "ICIJ — Panama Papers Global Overview"}, {"url": "https://www.pbs.org/wgbh/frontline/article/whats-known-about-putins-wealth-after-the-panama-papers/", "date": "2016", "name": "PBS Frontline — Putin''s Wealth After the Panama Papers"}, {"url": "https://www.opcw.org/media-centre/featured-topics/case-mr-alexei-navalny", "date": "2020", "name": "OPCW — Case of Mr. Alexei Navalny"}]'::jsonb
),
(
  'JACQUES CHIRAC',
  'Former President of France (1995–2007)',
  'Criminal Conviction for Embezzlement — First French President Convicted Since WWII',
  'HIGH',
  'On December 15, 2011, the Paris Criminal Court convicted Jacques Chirac of embezzlement of public funds, abuse of trust, and illegal conflict of interest — making him the first former French head of state since Marshal Philippe Petain to be criminally convicted, and the first president of France''s Fifth Republic (1958–present) to face a criminal conviction. The offenses arose from his tenure as Mayor of Paris (1977–1995), during which the Paris city government created more than two dozen fictitious municipal positions whose holders were in fact full-time workers for Chirac''s political party, the Rally for the Republic (RPR), paid with approximately $1.8 million in public municipal funds. Chirac received a two-year suspended prison sentence. He did not appeal, stating he lacked the strength to fight before new judges, and died on September 26, 2019. Notably, the prosecution itself had requested acquittal on grounds of insufficient evidence of intentional wrongdoing; the court rejected that position and convicted him regardless.',
  '["Paris Criminal Court convicted Chirac Dec 15, 2011 on two counts: embezzlement/abuse of trust for 21 fictitious RPR employees paid by Paris city treasury, and illegal conflict of interest for 7 additional positions", "Court: ''Jacques Chirac violated the trust that is expected of public officials tasked with safeguarding public funds''", "Approximately $1.8 million in Paris municipal funds paid to individuals performing no municipal work — salaries funded full-time RPR political party staff", "Scheme operated late 1980s–1995 during Chirac''s tenure as Mayor of Paris", "First President of France''s Fifth Republic prosecuted and convicted — first French head of state convicted since Petain''s 1945 Nazi collaboration conviction", "Prosecution itself requested acquittal; court rejected and convicted on both counts; Chirac accepted the verdict and did not appeal"]'::jsonb,
  '["CONVICTED — EMBEZZLEMENT & ABUSE OF TRUST", "FIRST FIFTH REPUBLIC PRESIDENT CONVICTED", "2-YEAR SUSPENDED SENTENCE"]'::jsonb,
  'Paris Criminal Court conviction of December 15, 2011 on two counts: embezzlement/abuse of trust for 21 fictitious RPR political party employees paid by the Paris city treasury, and illegal conflict of interest for 7 additional fictitious positions. Court statement: "Jacques Chirac violated the trust that is expected of public officials tasked with safeguarding public funds." Documentation of approximately $1.8 million in Paris municipal funds paid to individuals performing no municipal work — salaries funded full-time RPR political party staff. The scheme operated between the late 1980s and 1995 during Chirac''s tenure as Mayor of Paris. Notable that the prosecution requested acquittal; the court rejected that position and convicted on both counts.',
  '[{"url": "https://www.bbc.com/news/world-europe-16194089", "date": "2011-12-15", "name": "BBC — French Ex-President Chirac Guilty of Corruption"}, {"url": "https://www.reuters.com/article/world/french-ex-president-chirac-convicted-in-graft-trial-idUSTRE7BE0M4/", "date": "2011-12-15", "name": "Reuters — Chirac Convicted in Graft Trial"}, {"url": "https://www.npr.org/sections/thetwo-way/2011/12/15/143790539/former-french-president-chirac-found-guilty-of-corruption", "date": "2011-12-15", "name": "NPR — Chirac Found Guilty of Corruption"}, {"url": "https://www.nytimes.com/2011/12/16/world/europe/chirac-found-guilty-in-political-funding-case.html", "date": "2011-12-15", "name": "New York Times — Chirac Found Guilty in Political Funding Case"}]'::jsonb
),
(
  'ELIZABETH HOLMES',
  'Former CEO of Theranos',
  'Theranos Blood-Testing Fraud — Convicted, 11 Years Federal Prison',
  'CRITICAL',
  'Elizabeth Holmes founded Theranos in 2003 and built it into a $9 billion Silicon Valley company by falsely representing that her proprietary "Edison" device could accurately run hundreds of diagnostic blood tests from a single finger-prick sample. In reality, the technology never functioned as claimed; Theranos ran most tests on commercially available Siemens and other machines and falsified results. Investors collectively lost over $140 million proven at trial. Patients received inaccurate diagnostic results for conditions including cancer, HIV, and diabetes. Holmes was convicted by a federal jury on January 3, 2022, and sentenced to 135 months (11 years, 3 months) in federal prison on November 18, 2022 — the largest fraud sentence in Silicon Valley history. The Ninth Circuit Court of Appeals upheld the convictions and $452 million restitution order in February 2025.',
  '["Theranos falsely represented Edison device to investors, DoD, Walgreens, and Safeway as capable of hundreds of tests from finger-prick — it could not; most tests run on commercial machines", "Company valued at ~$9 billion at peak (2013–2015); Holmes''s personal net worth estimated at $4.5 billion; proven investor losses exceeded $140 million", "Patients received inaccurate results for cancer, HIV, and diabetes; one pregnant patient falsely told she had miscarried", "Jury verdict Jan 3, 2022: Guilty on 1 count conspiracy to commit wire fraud (investors) and 3 counts wire fraud (individual investors); Case: U.S. v. Holmes, No. 5:18-cr-00258 (N.D. Cal.)", "Sentence Nov 18, 2022: 135 months federal prison; $452 million restitution (shared with co-defendant Balwani)", "9th Circuit upheld convictions and restitution order February 24, 2025"]'::jsonb,
  '["CONVICTED — WIRE FRAUD & CONSPIRACY", "135 MONTHS FEDERAL PRISON", "$452M RESTITUTION"]'::jsonb,
  'Theranos falsely represented its Edison device to investors, the Department of Defense, and healthcare partners as capable of running hundreds of tests from a finger-prick sample; it could not; the company ran most tests on standard commercial machines. Company valued at approximately $9 billion at peak; proven investor losses exceeded $140 million. Patients received inaccurate test results for serious conditions including cancer, HIV, and diabetes. Federal charges filed June 14, 2018; jury verdict January 3, 2022: Guilty on 1 count conspiracy to commit wire fraud and 3 counts wire fraud. Sentence November 18, 2022: 135 months federal prison; $452 million restitution. 9th Circuit upheld convictions and restitution order February 24, 2025.',
  '[{"url": "https://www.justice.gov/usao-ndca/pr/elizabeth-holmes-sentenced-more-11-years-defrauding-theranos-investors-hundreds", "date": "2022-11-18", "name": "DOJ — Holmes Sentenced to More Than 11 Years"}, {"url": "https://www.justice.gov/usao-ndca/pr/theranos-founder-elizabeth-holmes-found-guilty-investor-fraud", "date": "2022-01-04", "name": "DOJ — Holmes Found Guilty of Investor Fraud"}, {"url": "https://www.justice.gov/usao-ndca/us-v-elizabeth-holmes-et-al", "date": "2022", "name": "DOJ — U.S. v. Elizabeth Holmes Case Page"}]'::jsonb
),
(
  'BERNIE MADOFF',
  'Former Chairman of NASDAQ / Bernard L. Madoff Investment Securities',
  'Largest Ponzi Scheme in Financial History — Convicted, 150 Years, $170B Forfeiture',
  'CRITICAL',
  'Bernard Madoff ran the largest known Ponzi scheme in financial history for at least two decades through his investment advisory operation within Bernard L. Madoff Investment Securities (BLMIS). He never invested client funds as promised, instead using new deposits to pay existing clients while generating fabricated account statements. At the time of his December 2008 arrest, client accounts showed a fictitious balance of approximately $64.8 billion; actual principal losses to approximately 4,800 client accounts totaled approximately $17 billion. Victims included charitable foundations, pension funds, hedge funds, and thousands of individual retirees. Madoff pleaded guilty on March 12, 2009 to 11 federal felony counts and was sentenced to 150 years — the statutory maximum — and ordered to forfeit $170,799,000,000. He died in federal prison on April 14, 2021. The SEC had received credible written warnings from analyst Harry Markopolos as early as 2000 and failed to investigate adequately, a documented institutional failure.',
  '["Scheme ran 20+ years; client statements showed ~$64.8 billion in fictitious balances; actual principal loss ~$17 billion across ~4,800 accounts", "Victims included Elie Wiesel''s Foundation for Humanity ($15.2M lost), banks, hedge funds, and thousands of individual retirees", "Confessed to sons Dec 10, 2008; they reported him to FBI; arrested Dec 11, 2008", "Guilty plea March 12, 2009 to all 11 counts: securities fraud, investment adviser fraud, mail fraud, wire fraud, money laundering (3 counts), false statements, perjury, false SEC filings, theft from employee benefit plan", "Sentence June 29, 2009: 150 years (statutory max); $170.8 billion forfeiture; Judge Chin: ''extraordinarily evil'' — ''no other white collar case is comparable''", "SEC received written warnings from analyst Harry Markopolos beginning 2000 and failed to investigate — documented systemic institutional failure"]'::jsonb,
  '["CONVICTED — 11 FEDERAL FELONIES", "150 YEARS / $170.8B FORFEITURE", "SEC IGNORED WARNINGS FOR 8+ YEARS"]'::jsonb,
  'Madoff''s scheme running for at least two decades; client statements showing approximately $64.8 billion in fictitious account balances; actual principal loss approximately $17 billion across approximately 4,800 client accounts. Guilty plea March 12, 2009 to all 11 counts before Judge Denny Chin: securities fraud, investment adviser fraud, mail fraud, wire fraud, money laundering (3 counts), false statements, perjury, false SEC filings, and theft from an employee benefit plan. Sentence June 29, 2009: 150 years (statutory maximum); forfeiture of $170,799,000,000; Judge Chin called it "extraordinarily evil" and stated "no other white collar case is comparable in terms of the scope, duration and enormity of the fraud." SEC received credible written warnings from analyst Harry Markopolos beginning in 2000 and failed to investigate adequately.',
  '[{"url": "https://www.justice.gov/archive/usao/nys/pressreleases/June09/madoffbernardsentencingpr.pdf", "date": "2009-06-29", "name": "DOJ — Bernard Madoff Sentenced to 150 Years"}, {"url": "https://www.justice.gov/archive/usao/nys/pressreleases/March09/madoffbernardpleapr.pdf", "date": "2009-03", "name": "DOJ — Madoff Pleads Guilty"}, {"url": "https://www.justice.gov/usao-sdny/file/762801/dl?inline=", "date": "2009-06-26", "name": "DOJ — Government Sentencing Memorandum"}, {"url": "https://www.justice.gov/sites/default/files/usao-sdny/legacy/2012/04/16/062909sentencing.pdf", "date": "2009-06-29", "name": "DOJ — Sentencing Transcript"}, {"url": "https://www.justice.gov/usao-sdny/programs/victim-witness-services/united-states-v-bernard-l-madoff-and-related-cases", "date": "2009", "name": "DOJ — U.S. v. Madoff Case Overview"}]'::jsonb
),
(
  'KENNETH LAY & JEFFREY SKILLING',
  'Former CEO & Former President of Enron Corporation',
  'Enron Accounting Fraud — Convicted 2006, Largest Corporate Bankruptcy of Its Era',
  'CRITICAL',
  'Kenneth Lay and Jeffrey Skilling presided over one of the largest corporate fraud schemes in U.S. history, systematically deceiving investors, the SEC, and the public about Enron''s financial performance through the use of special purpose entities to conceal debt, fraudulent mark-to-market accounting that booked projected future profits as current revenues, and false representations at analyst calls and press conferences. Enron filed for bankruptcy on December 2, 2001 — then the largest corporate bankruptcy in U.S. history — destroying approximately $74 billion in shareholder value and wiping out the retirement savings of thousands of employees. Both executives were convicted by a federal jury on May 25, 2006. Lay died before sentencing, vacating his conviction; Skilling was sentenced to 24 years and 4 months, later reduced to 14 years, and released in February 2019. Thirty additional Enron executives were charged; 16 pleaded guilty.',
  '["1999–2001: special purpose entities hid billions in debt; mark-to-market accounting booked projected future profits as current revenue", "Enron Chapter 11 bankruptcy Dec 2, 2001 — then largest in U.S. history; ~$74 billion shareholder value destroyed; thousands of employees lost retirement savings", "Federal jury verdict May 25, 2006: Lay convicted all 6 counts (conspiracy, 2 wire fraud, 3 securities fraud) plus 4 bank fraud/false statements in bench trial; Skilling convicted 19 of 28 counts", "Lay died of heart attack July 5, 2006 before sentencing; conviction vacated by law", "Skilling sentenced Oct 23, 2006 to 24 years 4 months and $45M forfeiture; resentenced 2013 to 14 years after Supreme Court narrowed honest services fraud statute; released Feb 2019", "30 additional Enron executives charged; 16 pleaded guilty"]'::jsonb,
  '["CONVICTED — CONSPIRACY & SECURITIES FRAUD", "$74B SHAREHOLDER VALUE DESTROYED", "30 EXECUTIVES CHARGED"]'::jsonb,
  'From approximately 1999–2001, Lay, Skilling, and other executives used special purpose entities to hide billions in debt from Enron''s public financial statements; fraudulent mark-to-market accounting booked projected future profits as current revenue. Enron filed for Chapter 11 bankruptcy December 2, 2001 — then the largest in U.S. history; approximately $74 billion in shareholder value destroyed; thousands of employees lost retirement savings held in company stock. Federal jury verdict May 25, 2006 (S.D. Tex., Judge Sim Lake): Lay convicted on all 6 counts (conspiracy, 2 wire fraud, 3 securities fraud) plus 4 additional bank fraud/false statements counts in separate bench trial; Skilling convicted on 19 of 28 counts. Lay died July 5, 2006 before sentencing. Skilling sentenced October 23, 2006 to 24 years 4 months and $45 million forfeiture; resentenced 2013 to 168 months; released February 2019.',
  '[{"url": "https://www.justice.gov/archive/opa/pr/2006/May/06_crm_328.html", "date": "2006-05-25", "name": "DOJ — Lay and Skilling Convicted"}, {"url": "https://www.justice.gov/archive/opa/pr/2006/October/06_crm_723.html", "date": "2006-10-23", "name": "DOJ — Skilling Sentenced to More Than 24 Years"}, {"url": "https://www.justice.gov/criminal/criminal-vns/case/united-states-v-jeffrey-k-skilling", "date": "2013", "name": "DOJ — U.S. v. Skilling Resentencing"}, {"url": "https://www.justice.gov/archive/index-enron.html", "date": "2006", "name": "DOJ — Enron Case Archive"}]'::jsonb
);