/*
  # Enemies of Truth — Batch 1: Bush Sr, Bush Jr, Bill Clinton, Hillary Clinton, Cheney, LBJ

  1. New Entries in `enemies_of_truth`
    - George H.W. Bush (CRITICAL): Iran-Contra diary cover-up, pardon corruption, Nayirah testimony fraud
    - George W. Bush (CRITICAL): Iraq War false WMD intelligence, CIA torture program authorization
    - Bill Clinton (CRITICAL): Impeachment for perjury/obstruction, Marc Rich pardon corruption, Epstein flight logs
    - Hillary Clinton (HIGH): Private email server classified material mishandling, Benghazi security failures
    - Dick Cheney (CRITICAL): Torture program authorization, Halliburton no-bid contracts, Plame affair
    - Lyndon B. Johnson (CRITICAL): Gulf of Tonkin deception — NSA declassified documents proving second attack never occurred

  2. Security
    - No schema changes; inserting into existing RLS-enabled table
*/

INSERT INTO enemies_of_truth (name, title, subtitle, severity, summary, key_facts, status_tags, evidence_documented, sources) VALUES
(
  'GEORGE H.W. BUSH',
  'Former President of the United States (1989–1993)',
  'Iran-Contra Diary Cover-Up, Pardon Corruption & Nayirah Testimony Fraud',
  'CRITICAL',
  'George H.W. Bush served as Vice President during the Iran-Contra affair (1984–1986), in which the Reagan administration secretly sold weapons to Iran and illegally funneled proceeds to Contra rebels in Nicaragua. Independent Counsel Lawrence Walsh''s final report concluded that Bush''s knowledge of the operation was substantially greater than his public "out of the loop" claim — a claim directly contradicted by his own diary, which he withheld from investigators for over five years despite formal document requests. On December 24, 1992, Bush issued blanket pardons to six Iran-Contra defendants, including former Defense Secretary Caspar Weinberger, whose trial was scheduled for January 5, 1993 — a trial in which Bush was expected to be called as a witness. Separately, Bush''s administration relied on fabricated congressional testimony from "Nayirah" — later revealed to be the daughter of Kuwait''s ambassador to the United States — as a justification for the Gulf War, a deception organized by the PR firm Hill & Knowlton and repeated by Bush himself at least five times before the Senate authorization vote.',
  '["Bush''s diary entry of November 5, 1986 reads: ''I''m one of the few people that know fully the details'' — directly contradicting his ''out of the loop'' claim", "Walsh''s office issued a formal document request March 27, 1987 covering all personal records, notes, diaries; diary not disclosed until December 11, 1992 — over five years later", "Proclamation 6518 (Dec 24, 1992): pardoned Weinberger, Abrams, Clarridge, Fiers, George, McFarlane — 12 days before Weinberger trial where Bush was expected witness", "Walsh: ''The Iran-contra cover-up, which has continued for more than six years, has now been completed with the pardon of Caspar Weinberger''", "''Nayirah'' was Nayirah al-Sabah, daughter of Kuwait''s ambassador; testimony arranged by Hill & Knowlton for $10M fee from Kuwaiti government-funded front group", "Fabricated incubator story cited by at least 6 U.S. Senators and repeated by Bush at least 5 times before the 52–47 Senate vote to authorize force (Jan 12, 1991)"]'::jsonb,
  '["PARDONED CO-CONSPIRATORS", "DIARY WITHHELD 5+ YEARS", "FABRICATED WAR TESTIMONY"]'::jsonb,
  'Bush''s diary entry of November 5, 1986 stating "I''m one of the few people that know fully the details," directly contradicting years of public "out of the loop" claims. Independent Counsel Walsh''s final report documenting that Bush''s knowledge was substantially greater than publicly claimed and that his diary was withheld from investigators for over five years despite formal document requests issued March 27, 1987. Proclamation 6518 (December 24, 1992) granting full pardons to six Iran-Contra defendants including Caspar Weinberger, whose trial was scheduled for January 5, 1993 — a trial where Bush was an expected witness. Walsh''s formal condemnation: "The Iran-contra cover-up, which has continued for more than six years, has now been completed with the pardon of Caspar Weinberger." Nayirah al-Sabah''s October 10, 1990 testimony before the Congressional Human Rights Caucus, arranged by Hill & Knowlton for a $10 million fee from Citizens for a Free Kuwait. Documentation that the fabricated incubator story was cited by at least six U.S. Senators and repeated by Bush at least five times before the Senate''s 52–47 vote to authorize force on January 12, 1991.',
  '[{"url": "https://irp.fas.org/offdocs/walsh/chap_28.htm", "date": "1993", "name": "Walsh Final Report — Chapter 28: George Bush"}, {"url": "https://irp.fas.org/offdocs/walsh/part_xi.htm", "date": "1993", "name": "Walsh Final Report — Part XI: Concluding Observations"}, {"url": "https://www.govinfo.gov/content/pkg/STATUTE-107/pdf/STATUTE-107-Pg2606.pdf", "date": "1992-12-24", "name": "Proclamation 6518 — Executive Clemency for Weinberger and Others"}, {"url": "https://www.govinfo.gov/content/pkg/CREC-1994-06-16/html/CREC-1994-06-16-pt1-PgS6.htm", "date": "1994-06-16", "name": "Congressional Record Vol 140, Issue 76 — Nayirah Testimony"}, {"url": "https://wikileaks.org/plusd/cables/90BAGHDAD4237_a.html", "date": "1990-07-25", "name": "Glaspie Cable (90BAGHDAD4237_a) — State Dept"}]'::jsonb
),
(
  'GEORGE W. BUSH',
  'Former President of the United States (2001–2009)',
  'Iraq War False WMD Intelligence & CIA Torture Program Authorization',
  'CRITICAL',
  'The Bush administration made the case for the March 2003 invasion of Iraq using intelligence claims that were subsequently found by multiple official investigations to be unsubstantiated, contradicted, or non-existent. The CIA''s Iraq Survey Group (Duelfer Report, 2004) found no active WMD stockpiles of any kind in Iraq. The Senate Intelligence Committee''s bipartisan Phase II report (2008) concluded the administration "repeatedly presented intelligence as fact when in reality it was unsubstantiated, contradicted, or even non-existent." A classified British government memorandum from July 23, 2002 — eight months before the invasion — recorded that U.S. intelligence was being "fixed around the policy." Simultaneously, the Bush administration authorized a covert CIA detention and interrogation program that the Senate Intelligence Committee''s 2014 study — drawing on more than 6 million pages of internal CIA records — found to constitute torture, to have been ineffective at producing intelligence, and to have involved systematic deception of Congress, the White House, and the public.',
  '["Downing Street Memo (July 23, 2002): MI6 Director Dearlove reported ''the intelligence and facts were being fixed around the policy''", "Senate Intelligence Committee Phase II Report (June 5, 2008): Iraq-al-Qaeda claims ''were not supported by the intelligence''; WMD-to-terrorist claims ''contradicted'' by intelligence", "Duelfer Report (Sept 2004): No active WMD stockpiles; Powell''s ''mobile biological labs'' were hydrogen/balloon production units", "Senate Intelligence Committee 2014 study (6,700+ pages): CIA techniques ''brutal and far worse than the CIA represented to policymakers'' and NOT effective", "At least 26 detainees wrongfully held; at least one died of hypothermia at Facility COBALT (Nov 2002)", "CIA did not brief the President on specific techniques before April 2006; full Senate committee not briefed until Sept 6, 2006"]'::jsonb,
  '["INVASION BASED ON FALSE INTELLIGENCE", "CIA TORTURE PROGRAM", "SYSTEMATIC DECEPTION OF CONGRESS"]'::jsonb,
  'The Downing Street Memo (July 23, 2002) recording MI6 Director Richard Dearlove''s assessment: "The intelligence and facts were being fixed around the policy." Senate Intelligence Committee Phase II Report (June 5, 2008) finding administration statements suggesting Iraq-al-Qaeda partnership "were not supported by the intelligence" and claims Saddam was prepared to give WMD to terrorists were "contradicted" by available intelligence. The Duelfer Report (September 2004) finding Iraq had no active stockpiles of chemical, biological, nuclear, or radiological weapons at invasion time. The Senate Intelligence Committee''s 2014 study (6,700+ pages, 6.3 million CIA records reviewed) finding the CIA''s enhanced interrogation techniques were "brutal and far worse than the CIA represented to policymakers" and were NOT effective. Documentation of at least 26 wrongfully held detainees and at least one death from hypothermia at Facility COBALT in November 2002. CIA briefing records showing the President was not briefed on specific techniques before April 2006 and the full Senate committee not until September 6, 2006.',
  '[{"url": "https://www.intelligence.senate.gov/2008/06/05/press-senate-intelligence-committee-unveils-final-phase-ii-reports-prewar-iraq-intelligence/", "date": "2008-06-05", "name": "Senate Intelligence Committee — Phase II Report on Iraq Intelligence"}, {"url": "https://www.govinfo.gov/app/details/GPO-DUELFERREPORT", "date": "2004-09", "name": "Iraq Survey Group Final Report (Duelfer Report)"}, {"url": "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB328/II-Doc14.pdf", "date": "2002-07-23", "name": "Downing Street Memo — National Security Archive"}, {"url": "https://www.intelligence.senate.gov/wp-content/uploads/2024/08/sites-default-files-press-findings-and-conclusions.pdf", "date": "2014-12", "name": "SSCI CIA Detention & Interrogation Program — Findings"}, {"url": "https://www.intelligence.senate.gov/wp-content/uploads/2024/08/sites-default-files-press-executive-summary-0.pdf", "date": "2014-12", "name": "SSCI CIA Detention & Interrogation Program — Executive Summary"}, {"url": "https://2001-2009.state.gov/secretary/former/powell/remarks/2003/17300.htm", "date": "2003-02-05", "name": "Powell Remarks to UN Security Council"}]'::jsonb
),
(
  'BILL CLINTON',
  'Former President of the United States (1993–2001)',
  'Impeachment for Perjury & Obstruction, Marc Rich Pardon Corruption, Epstein Flight Logs',
  'CRITICAL',
  'Bill Clinton became the second U.S. president in history to be impeached when the House voted on December 19, 1998 to approve two articles — perjury before a grand jury (228–206) and obstruction of justice (221–212) — arising from his false testimony under oath about his relationship with White House intern Monica Lewinsky. He was subsequently found in civil contempt of court by Judge Susan Webber Wright and had his Arkansas law license suspended for five years. On his final day in office, Clinton granted a full, unconditional pardon to Marc Rich, an international fugitive facing 51 federal counts who had fled to Switzerland in 1983; Rich''s ex-wife Denise had donated approximately $450,000 to the Clinton presidential library project, and the pardon petition bypassed the Justice Department''s standard process entirely. Flight logs entered into evidence in United States v. Maxwell and documents released under the Epstein Transparency Act confirm Clinton traveled on Jeffrey Epstein''s private jet on multiple occasions between 2002 and 2003.',
  '["Starr Report (H. Doc. 105-310, Sept 9, 1998): transmitted 11 potentially impeachable acts including perjury in civil deposition (Jan 17, 1998) and before grand jury (Aug 17, 1998)", "Judge Susan Webber Wright: civil contempt for ''false, misleading, and evasive answers'' — $90,686 fine; Arkansas Supreme Court: 5-year law license suspension, $25,000 fine", "Marc Rich pardon petition submitted directly to White House by attorney Jack Quinn, bypassing DOJ Pardon Attorney entirely; Pardon Attorney Roger Adams: ''there was never any mention of Rich being a fugitive''", "Denise Rich donated ~$450,000 to Clinton presidential library and ~$450,000 to Democratic causes; SDNY opened criminal investigation into whether pardon was purchased (closed 2005 without charges)", "DOJ Exhibit GX 662-RR in U.S. v. Maxwell confirmed Clinton''s name in Epstein aircraft flight logs (2001–2003)", "Epstein Transparency Act documents (Dec 2025) confirmed Clinton''s presence in Epstein flight records; Secret Service detail documented on every flight leg"]'::jsonb,
  '["IMPEACHED — PERJURY & OBSTRUCTION", "EPSTEIN FLIGHT LOGS CONFIRMED", "MARC RICH PARDON BYPASSED DOJ"]'::jsonb,
  'The Starr Report (H. Doc. 105-310, September 9, 1998) transmitting 11 potentially impeachable acts to Congress. House impeachment vote December 19, 1998: Article I perjury (228–206), Article III obstruction (221–212). Judge Susan Webber Wright''s civil contempt finding for "false, misleading, and evasive answers" with $90,686 fine. Arkansas Supreme Court 5-year law license suspension and $25,000 fine. Marc Rich pardon submitted by attorney Jack Quinn directly to the White House bypassing the DOJ Pardon Attorney; U.S. Pardon Attorney Roger Adams testified "there was never any mention of Rich being a fugitive." Denise Rich donations of approximately $450,000 to the Clinton library and $450,000 to Democratic causes. DOJ Exhibit GX 662-RR in United States v. Maxwell confirming Clinton''s name in Epstein aircraft flight logs covering 2001–2003. Epstein Transparency Act documents (December 2025) confirming Clinton''s presence in Epstein''s flight records with Secret Service detail documented on every leg.',
  '[{"url": "https://www.govinfo.gov/content/pkg/CDOC-105hdoc310/pdf/CDOC-105hdoc310.pdf", "date": "1998-09-09", "name": "Starr Report (H. Doc. 105-310)"}, {"url": "https://www.govinfo.gov/content/pkg/GPO-CDOC-106sdoc3/pdf/GPO-CDOC-106sdoc3-1.pdf", "date": "1999", "name": "Senate Impeachment Trial Record (S. Doc. 106-3)"}, {"url": "https://www.govinfo.gov/content/pkg/CHRG-107hhrg75593/pdf/CHRG-107hhrg75593.pdf", "date": "2001", "name": "House Committee on Government Reform — Marc Rich Hearing"}, {"url": "https://www.justice.gov/pardon/pardons-granted-president-william-j-clinton-1993-2001", "date": "2001-01-20", "name": "DOJ — Pardons Granted by President Clinton"}, {"url": "https://www.justice.gov/ag/media/1391276/dl?inline", "date": "2026", "name": "DOJ — Exhibit GX 662-RR (Flight Log, U.S. v. Maxwell)"}, {"url": "https://www.justice.gov/epstein/doj-disclosures", "date": "2026", "name": "DOJ — Epstein Disclosures"}]'::jsonb
),
(
  'HILLARY CLINTON',
  'Former Secretary of State (2009–2013)',
  'Private Server Classified Material Mishandling & Benghazi Security Failures',
  'HIGH',
  'As Secretary of State (2009–2013), Hillary Clinton exclusively used a private email server registered to "clintonemail.com" and hosted at her Chappaqua, New York residence for all official government business, without approval from — or notification to — the State Department''s Chief Information Officer or assistant secretary for diplomatic security. The State Department Inspector General found this violated federal records management policies and that such approval "would not have been granted" had it been sought. The FBI''s investigation found 110 email chains contained information classified at the time of transmission, including eight chains at the Top Secret/Special Access Program level. FBI Director James Comey''s initial draft described Clinton''s handling as "grossly negligent" — the statutory standard for criminal liability — before the language was changed to "extremely careless." Separately, the Accountability Review Board found "grossly inadequate" security posture at the Benghazi diplomatic compound prior to the September 11, 2012 attack that killed four Americans including Ambassador J. Christopher Stevens.',
  '["State Dept IG Report (ESP-16-03, May 2016): Clinton ''did not comply with the Department''s policies''; server ''would not have received approval''; staff told ''never speak of the Secretary''s personal email system again''", "FBI found 110 email chains classified at time sent, including 8 at Top Secret/Special Access Program level — the highest classification tier", "Comey''s May 2, 2016 draft used ''grossly negligent'' (statutory criminal standard under 18 U.S.C. 793(f)); changed to ''extremely careless'' in June 10, 2016 revision", "DOJ IG June 2018 report: Comey''s unilateral announcement usurped AG authority and violated DOJ policy; FBI agents sent texts expressing strong support for Clinton during investigation", "Benghazi ARB (Dec 19, 2012): security failures ''systemic''; security posture ''grossly inadequate for the threat environment''", "Senate Intelligence Committee bipartisan Benghazi report (Jan 15, 2014): State Dept ''should have increased its security posture more significantly''"]'::jsonb,
  '["NO CRIMINAL CHARGES", "110 CLASSIFIED CHAINS ON PRIVATE SERVER", "GROSSLY NEGLIGENT → EXTREMELY CARELESS"]'::jsonb,
  'State Department Inspector General Report ESP-16-03 (May 2016) finding Clinton "did not comply with the Department''s policies" implementing the Federal Records Act, that her server would not have received approval, and that staff who raised concerns were told to "never speak of the Secretary''s personal email system again." FBI investigation finding 110 email chains classified at time of transmission, including 8 at Top Secret/Special Access Program level. Senate Judiciary Committee documentation confirming Comey''s May 2, 2016 draft used "grossly negligent" (statutory criminal standard under 18 U.S.C. 793(f)), changed to "extremely careless" in June 10, 2016 revision. DOJ Inspector General June 2018 report finding Comey''s announcement usurped Attorney General authority and violated DOJ policy, and that FBI agents sent texts expressing strong support for Clinton during the investigation. Benghazi Accountability Review Board (December 19, 2012) finding security failures "systemic" and posture "grossly inadequate for the threat environment." Senate Intelligence Committee bipartisan report (January 15, 2014) concluding State Department "should have increased its security posture more significantly."',
  '[{"url": "https://www.justice.gov/file/1071991/download", "date": "2018-06-14", "name": "DOJ OIG — Review of FBI/DOJ Actions in Advance of 2016 Election"}, {"url": "https://nsarchive.gwu.edu/document/21788-document-12", "date": "2016-05", "name": "State Dept OIG Report ESP-16-03 — Email Records"}, {"url": "https://www.judiciary.senate.gov/press/rep/releases/clinton-grossly-negligent-in-comeys-draft-statement-on-email-probe", "date": "2017", "name": "Senate Judiciary Committee — Grossly Negligent in Comey Draft"}, {"url": "https://2009-2017.state.gov/documents/organization/202446.pdf", "date": "2012-12-19", "name": "Benghazi Accountability Review Board Report"}, {"url": "https://www.intelligence.senate.gov/2014/01/15/press-senate-intelligence-committee-releases-declassified-bipartisan-report-benghazi-terrorist/", "date": "2014-01-15", "name": "Senate Intelligence Committee — Benghazi Report"}, {"url": "https://www.govinfo.gov/content/pkg/CRPT-114hrpt848/pdf/CRPT-114hrpt848.pdf", "date": "2016-06-28", "name": "House Select Committee on Benghazi — Final Report"}]'::jsonb
),
(
  'DICK CHENEY',
  'Former Vice President of the United States (2001–2009)',
  'Torture Program Authorization, Halliburton No-Bid Contracts & the Plame Affair',
  'CRITICAL',
  'Dick Cheney served as Vice President from 2001 to 2009 and is documented across three major scandal domains established by official investigations. As a leading advocate of the CIA''s post-9/11 enhanced interrogation program, he was repeatedly briefed on techniques that the Senate Intelligence Committee''s 2014 study — drawing on 6.3 million pages of CIA records — found were "brutal and far worse than the CIA represented to policymakers" and were not effective at producing actionable intelligence. Prior to assuming the Vice Presidency, Cheney had served as CEO of Halliburton (1995–2000); in March 2003, the Army Corps of Engineers awarded Halliburton subsidiary KBR a no-bid $7 billion Iraq oil infrastructure contract while Cheney continued to receive deferred compensation from the company. His chief of staff I. Lewis "Scooter" Libby was convicted in 2007 of perjury, obstruction of justice, and making false statements in connection with the leak of covert CIA officer Valerie Plame''s identity, after Plame''s husband publicly challenged the administration''s Iraq intelligence.',
  '["Senate Intelligence Committee 2014 study: Cheney identified as ''fervent advocate'' for CIA enhanced interrogation; CIA briefings to Cheney ''repeatedly misrepresented the program''s effectiveness'' (SSCI Finding #7)", "Techniques documented: waterboarding inducing convulsions, sleep deprivation up to 180 hours, rectal feeding without medical necessity, threats to harm detainees'' families, at least one detainee death from hypothermia", "Cheney CEO of Halliburton 1995–2000; Army contracting officer Bunnatine Greenhouse filed formal complaint that March 2003 no-bid $7B KBR contract was improperly awarded", "Pentagon auditors: KBR did not adequately account for $1.8 billion+ billed to U.S. government under Iraq contracts", "Scooter Libby convicted March 6, 2007: 2 counts perjury, 1 count obstruction, 1 count false statements — all from investigation of Valerie Plame identity leak", "Cheney publicly stated regarding the torture program: ''I would do it again in a minute''"]'::jsonb,
  '["CIA TORTURE ADVOCATE", "$7B NO-BID HALLIBURTON CONTRACT", "LIBBY CONVICTED — PLAME LEAK"]'::jsonb,
  'Senate Intelligence Committee 2014 study identifying Cheney as a "fervent advocate" for the CIA''s enhanced interrogation techniques with CIA briefing documents that "repeatedly misrepresented the program''s effectiveness." Documented techniques including waterboarding inducing convulsions, sleep deprivation up to 180 hours, rectal feeding without medical necessity, threats to harm detainees'' family members, and at least one detainee death from hypothermia. Army contracting officer Bunnatine Greenhouse''s formal complaint that the March 2003 no-bid $7 billion KBR contract was awarded improperly. Pentagon audit findings that KBR did not adequately account for more than $1.8 billion billed to the U.S. government. Scooter Libby conviction on March 6, 2007 on 2 counts of perjury, 1 count of obstruction of justice, and 1 count of making false statements arising from investigation into the leak of covert CIA officer Valerie Plame Wilson''s identity.',
  '[{"url": "https://www.intelligence.senate.gov/sites/default/files/publications/CRPT-113srpt288.pdf", "date": "2014-12", "name": "SSCI — CIA Detention and Interrogation Program Study"}, {"url": "https://www.justice.gov/archive/usao/dc/Divisions/Public_Interest/Plame_Files/LIBBY_SENTENCING_MEMORANDUM_OF_USA.PDF", "date": "2007", "name": "DOJ — United States v. Libby Sentencing Memorandum"}, {"url": "https://publicintegrity.org/national-security/documents-reveal-concern-regarding-halliburton-contracts/", "date": "2003", "name": "Center for Public Integrity — Halliburton Contract Documents"}, {"url": "https://www.cbsnews.com/news/halliburton-whistleblower-on-exposing-7-billion-no-bid-defense-contract-2019-06-30/", "date": "2019-06-30", "name": "CBS News — Halliburton Whistleblower"}]'::jsonb
),
(
  'LYNDON B. JOHNSON',
  'Former President of the United States (1963–1969)',
  'Gulf of Tonkin Deception — NSA Documents Prove Second Attack Never Occurred',
  'CRITICAL',
  'The Johnson administration presented Congress and the public with a fabricated account of a second North Vietnamese naval attack on August 4, 1964 — an attack that, according to a classified NSA historical study declassified in 2005, never took place. That false account was used to pass the Gulf of Tonkin Resolution (98–2 in the Senate) on August 7, 1964, which provided the legal authorization for the full-scale U.S. military commitment to Vietnam. NSA historian Robert J. Hanyok''s classified study concluded that nearly 90% of SIGINT intercepts contradicting the attack narrative were suppressed, that some signals were altered to show different receipt times, and that evidence was "cherry picked to deliberately distort the truth." President Johnson privately acknowledged his doubts about the attack to the National Security Council but proceeded with military retaliation and sought congressional authorization. The resulting conflict cost over 58,000 American lives and an estimated 2–3 million Vietnamese lives.',
  '["NSA historian Hanyok (written 2001, declassified 2005): the August 4, 1964 ''second attack'' never occurred — ''The overwhelming body of reports, if used, would have told the story that no attack occurred''", "Nearly 90% of SIGINT intercepts contradicting the attack narrative were suppressed; signals intercepts altered to show different receipt times", "Messages to Pentagon ''contained severe analytic errors, unexplained translation changes, and the conjunction of two messages into one translation'' (Hanyok)", "LBJ privately told NSC he doubted the attack had occurred, then proceeded with military retaliation and pushed Congress for authorization", "LBJ privately: ''Hell, those dumb, stupid sailors were just shooting at flying fish out there''", "Gulf of Tonkin Resolution passed 98–2 in Senate based on false premises — authorizing ''all necessary measures'' without formal declaration of war"]'::jsonb,
  '["FABRICATED CASUS BELLI", "NSA DOCUMENTS DECLASSIFIED 2005", "58,000+ AMERICAN LIVES LOST"]'::jsonb,
  'NSA historian Robert J. Hanyok''s classified study (written 2001, declassified 2005) concluding the August 4, 1964 "second attack" never occurred: "The overwhelming body of reports, if used, would have told the story that no attack occurred." Finding that nearly 90% of SIGINT intercepts contradicting the attack narrative were suppressed and signals intercepts were altered to show different receipt times. Messages sent to the Pentagon "contained severe analytic errors, unexplained translation changes, and the conjunction of two messages into one translation." LBJ Presidential Library recordings documenting Johnson''s private doubts. The Gulf of Tonkin Resolution passing 98–2 in the Senate on August 7, 1964 based on false premises, authorizing the President to "take all necessary measures" without a formal declaration of war.',
  '[{"url": "https://www.nsa.gov/portals/75/documents/news-features/declassified-documents/gulf-of-tonkin/articles/rel1_hanyok_article.pdf", "date": "2005", "name": "NSA Declassified — Hanyok Gulf of Tonkin Study"}, {"url": "https://www.usni.org/magazines/naval-history-magazine/2008/february/truth-about-tonkin", "date": "2008-02", "name": "Naval History Magazine — The Truth About Tonkin"}, {"url": "https://nsarchive.gwu.edu/briefing-book/vietnam/2019-08-01/gulf-tonkin-revisited", "date": "2019-08-01", "name": "National Security Archive — Gulf of Tonkin Revisited"}, {"url": "https://www.discoverlbj.org/collections/lbj-library-collections", "date": "1964", "name": "LBJ Presidential Library — Recordings Collection"}]'::jsonb
);